-- =========================================================
-- SEED: Tipps zu Item 1 (Nr. 11–50)
-- «In meinem Kurs haben Lernende die Möglichkeit, Wissen und Lernwege selbst zu bestimmen.»
-- =========================================================
INSERT INTO spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig) VALUES
(1, 11, 'Fragenbox einrichten',
 'Lernende bringen eigene Wissenslücken am besten selbst ein – sie wissen, was ihnen fehlt.',
 'Selbst eingebrachte Fragen erhöhen die Aufmerksamkeit, weil die Antwort persönlich relevant ist.',
 'Stellen Sie eine «Fragenbox» auf, aus der Sie regelmässig Themen für kommende Lektionen ziehen.',
 'In der Box landet ein Zettel von Frau M.: «Was sage ich, wenn das Paket nicht angekommen ist?» Sie greifen die Frage am nächsten Tag als Sprechanlass auf.',
 'Leeren Sie die Box sichtbar regelmässig, sonst verliert sie an Glaubwürdigkeit.'),
(1, 12, 'Eigene Beispielsätze bilden',
 'Sprache wird verankert, wenn sie aus dem eigenen Leben statt aus dem Lehrbuch stammt.',
 'Selbst formulierte Sätze sind bedeutungsvoller und werden besser behalten als übernommene.',
 'Lassen Sie Lernende eigene Beispielsätze statt vorgegebener bilden – zu jeder neuen Struktur einen Satz aus dem eigenen Alltag.',
 'Beim Üben von «weil» schreibt Herr N.: «Ich lerne Deutsch, weil ich arbeiten will.» Der Satz wird zum persönlichen Merksatz für die ganze Gruppe.',
 'Korrigieren Sie behutsam, damit der persönliche Gehalt nicht durch zu viel Rotstift verloren geht.'),
(1, 13, 'Stationenreihenfolge freigeben',
 'Lernwege müssen nicht linear sein – die Reihenfolge darf der eigenen Logik folgen.',
 'Freie Reihenfolge gibt Kontrolle und verhindert Wartezeiten und Leerlauf.',
 'Geben Sie die Reihenfolge mehrerer Stationen frei – jede/r beginnt, wo es passt, und arbeitet im eigenen Takt.',
 'Vier Stationen zum Thema Wohnen stehen bereit. Frau O. startet beim Mietvertrag, Herr P. beim Wortschatz – beide kommen ohne Stau durch.',
 'Sorgen Sie dafür, dass die Stationen unabhängig voneinander lösbar sind.'),
(1, 14, 'Alltagstexte einbringen',
 'Authentische Texte aus dem Leben der Lernenden sind die relevantesten Lernmaterialien.',
 'Echte Dokumente steigern Motivation, weil das Gelernte sofort im Alltag nützt.',
 'Lassen Sie Lernende wählen, welche Texte aus ihrem Alltag (Briefe, Plakate, Fotos) im Kurs bearbeitet werden.',
 'Frau Q. bringt einen Brief der Krankenkasse mit. Die Gruppe entschlüsselt ihn gemeinsam – plötzlich ist Behördendeutsch kein abstraktes Thema mehr.',
 'Klären Sie vorab, dass keine sensiblen persönlichen Daten geteilt werden müssen.'),
(1, 15, 'Schwierigkeitsstufe wählen',
 'Lernen gelingt am besten in der eigenen Zone der nächsten Entwicklung.',
 'Die selbst gewählte Stufe verhindert Über- wie Unterforderung und stärkt das Zutrauen.',
 'Bieten Sie verschiedene Schwierigkeitsstufen desselben Textes an und lassen Sie Lernende selbst einsteigen.',
 'Ein Text über das Wetter liegt in drei Versionen aus. Herr R. nimmt die leichte, Frau S. die mittlere – beide sprechen danach über denselben Inhalt.',
 'Vermeiden Sie eine sichtbare Hierarchie der Stufen, damit niemand sich abgewertet fühlt.'),
(1, 16, 'Redewendungen priorisieren',
 'Was zuerst gelernt wird, sollte dem unmittelbaren Bedarf der Gruppe entsprechen.',
 'Mitbestimmung über die Lernreihenfolge erhöht das Gefühl, ernst genommen zu werden.',
 'Lassen Sie die Gruppe entscheiden, welche Redewendungen sie zuerst lernen will.',
 'Aus einer Liste mit zehn Wendungen wählt die Gruppe «Können Sie das bitte wiederholen?» an erste Stelle – sie brauchen es täglich im Kurs selbst.',
 'Halten Sie die übrigen Wendungen sichtbar fest, damit klar ist: Sie kommen auch noch dran.'),
(1, 17, 'Hausaufgaben-Optionen',
 'Verschiedene Wege können zum selben Lernziel führen – auch ausserhalb des Kurses.',
 'Wahlfreiheit bei Hausaufgaben erhöht die Erledigungsquote, weil die Aufgabe zur Lebenssituation passt.',
 'Geben Sie für Hausaufgaben mehrere Optionen mit demselben Lernziel – etwa schreiben, aufnehmen oder ein Gespräch führen.',
 'Zum Ziel «Vergangenheit erzählen» wählt Frau T. eine Sprachnachricht, Herr U. einen kurzen Text – beide üben dasselbe.',
 'Stellen Sie sicher, dass alle Optionen mit den Mitteln der Lernenden machbar sind.'),
(1, 18, 'Wochenziel formulieren',
 'Selbst gesetzte Ziele sind verbindlicher als fremd gesetzte.',
 'Ein eigenes, aufgeschriebenes Ziel lenkt die Aufmerksamkeit und macht Fortschritt sichtbar.',
 'Lassen Sie Lernende ein persönliches Lernziel für die Woche formulieren und aufschreiben.',
 'Herr V. notiert: «Diese Woche frage ich im Laden nach dem Preis.» Am Freitag berichtet er, dass es geklappt hat.',
 'Helfen Sie, Ziele klein und konkret zu halten, sonst bleiben sie unerreichbar.'),
(1, 19, 'Abschluss frei wählen',
 'Lernende dürfen entscheiden, in welcher Fertigkeit sie ein Thema abrunden.',
 'Die Wahl des Abschlusses spielt zu den eigenen Stärken und schafft Erfolgserlebnisse.',
 'Bieten Sie an, ein Thema entweder schriftlich oder mündlich abzuschliessen.',
 'Zum Thema Bewerbung schreibt Frau W. einen kurzen Brief, während Herr X. das Vorstellungsgespräch übt – beide zeigen, was sie können.',
 'Achten Sie darauf, dass über die Zeit beide Fertigkeiten geübt werden, nicht nur die bequeme.'),
(1, 20, 'Eigenes Material einbringen',
 'Lieder, Serien und Apps aus der eigenen Welt sind starke, selbst gewählte Lernquellen.',
 'Material mit persönlichem Bezug wird intensiver genutzt und emotional verankert.',
 'Lassen Sie Lernende ihre eigenen Lieder, Serien oder Apps als Lernmaterial einbringen.',
 'Frau Y. bringt ein deutsches Lied mit, das sie im Radio mag. Sie hören es gemeinsam und sammeln daraus neue Wörter.',
 'Prüfen Sie das Material kurz vorab auf Eignung und Niveau.'),
(1, 21, 'Materialecke bereitstellen',
 'Eine offen zugängliche Materialecke ermöglicht selbstbestimmtes Schöpfen.',
 'Freier Zugriff fördert Eigeninitiative und Unabhängigkeit von der Kursleitung.',
 'Stellen Sie eine Materialecke bereit (Wörterbücher, Bildkarten, Tablets), aus der frei geschöpft wird.',
 'Während einer Schreibaufgabe holt sich Herr Z. selbst ein Bildwörterbuch aus der Ecke, statt zu warten, bis Sie kommen.',
 'Vereinbaren Sie einfache Regeln zum Zurücklegen, damit die Ecke ordentlich bleibt.'),
(1, 22, 'Erklärung bei Bedarf',
 'Lernende dürfen selbst spüren, wann sie eine Erklärung brauchen und wann nicht.',
 'Wer erst probiert und dann fragt, lernt nachhaltiger als wer alles vorab erklärt bekommt.',
 'Lassen Sie Lernende selbst entscheiden, wann sie eine Erklärung brauchen und wann sie zuerst probieren.',
 'Bei einer neuen Aufgabe legen Sie die Erklärkarte bereit, sagen aber: «Probieren Sie zuerst.» Frau A. schafft es allein, Herr B. greift zur Karte.',
 'Signalisieren Sie, dass Nachfragen kein Versagen ist, sondern eine Lernstrategie.'),
(1, 23, 'Tempo-Spuren anbieten',
 'Unterschiedliche Lerntempi brauchen unterschiedliche Wege durch denselben Stoff.',
 'Passende Spuren verhindern Langeweile bei Schnellen und Stress bei Langsamen.',
 'Bieten Sie «Express»- und «Vertiefungs»-Spuren für unterschiedliches Tempo an.',
 'Beim Thema Zahlen wählt die schnelle Frau C. die Express-Spur mit Zusatzaufgaben, Herr D. nimmt die Vertiefung mit mehr Übung.',
 'Stellen Sie sicher, dass die Express-Spur nicht als Belohnung und die Vertiefung nicht als Strafe wirkt.'),
(1, 24, 'Eigene Textfragen stellen',
 'Wer eigene Fragen an einen Text stellt, liest aktiver und verarbeitet tiefer.',
 'Selbst gestellte Fragen fördern Leseverstehen mehr als das Beantworten fremder Fragen.',
 'Lassen Sie Lernende eigene Fragen an einen Text formulieren, statt nur Ihre zu beantworten.',
 'Nach einem Text über den Wochenmarkt schreibt Frau E. die Frage: «Wann ist der Markt offen?» und stellt sie ihrer Nachbarin.',
 'Geben Sie anfangs Fragewörter als Stütze, bis das eigene Fragen sitzt.'),
(1, 25, 'Lernweg-Landkarte',
 'Der eigene Lernweg wird greifbar, wenn er sichtbar gemacht wird.',
 'Eine visuelle Landkarte stärkt das Bewusstsein für eigene Entscheidungen und Fortschritte.',
 'Geben Sie eine Themenlandkarte aus, auf der jede/r den eigenen Lernweg einzeichnet.',
 'Auf einer Karte mit Inseln (Wohnen, Arbeit, Gesundheit) zeichnet Herr F. seinen Weg ein und sieht, welche «Insel» als Nächstes dran ist.',
 'Halten Sie die Karte einfach, sonst wird das Einzeichnen selbst zur Hürde.'),
(1, 26, 'Echtes Formular wählen',
 'Üben wird relevant, wenn es am tatsächlich anstehenden Dokument geschieht.',
 'Die Arbeit am eigenen Formular verbindet Sprachlernen direkt mit der Alltagsbewältigung.',
 'Lassen Sie Lernende auswählen, mit welchem Behördenformular sie üben, und ihr echtes mitbringen.',
 'Frau G. bringt das Anmeldeformular der Gemeinde mit. Gemeinsam füllen Sie es Schritt für Schritt aus – sie kann es danach zu Hause selbst.',
 'Achten Sie auf Datenschutz: Persönliche Angaben können mit Platzhaltern geübt werden.'),
(1, 27, 'Aussprache-Zugänge öffnen',
 'Aussprache lässt sich über verschiedene Sinne und Methoden trainieren.',
 'Der selbst gewählte Übungsweg senkt die Hemmung, sich sprechend zu zeigen.',
 'Bieten Sie zur Aussprache mehrere Zugänge an: Nachsprechen, Aufnahme, Spiegel, App.',
 'Beim «ch»-Laut übt Herr H. mit dem Spiegel die Mundstellung, während Frau I. lieber eine App mit Hörvergleich nutzt.',
 'Sorgen Sie für eine vertrauensvolle Stimmung, damit sich niemand fürs Sprechen schämt.'),
(1, 28, 'Fehlerfokus selbst setzen',
 'Lernende können selbst einschätzen, welcher Fehler sie am meisten stört.',
 'Der selbst gewählte Fokus erhöht die Bereitschaft, gezielt an etwas zu arbeiten.',
 'Lassen Sie Lernende selbst bestimmen, welche Fehler sie zuerst angehen wollen.',
 'Frau J. sagt: «Die Artikel sind mein grösstes Problem.» Sie vereinbaren, eine Woche lang besonders auf der/die/das zu achten.',
 'Würdigen Sie, dass nicht jeder Fehler sofort verschwinden muss – Schwerpunkte genügen.'),
(1, 29, 'Padlet zum Teilen',
 'Digitale Pinnwände ermöglichen gemeinsames, selbstbestimmtes Sammeln von Material.',
 'Geteiltes Material stärkt das Gefühl, Teil einer lernenden Gemeinschaft zu sein.',
 'Stellen Sie ein digitales Padlet bereit, auf dem Lernende Lernmaterial sammeln und teilen.',
 'Herr K. postet ein Foto eines Strassenschilds mit Frage. Andere antworten – das Padlet wird zur gemeinsamen Wortschatzsammlung.',
 'Klären Sie kurz die Bedienung, damit die Technik niemanden ausschliesst.'),
(1, 30, 'Gesprächsform wählen',
 'Ein Gespräch kann vorbereitet, frei oder aufgenommen geübt werden.',
 'Die selbst gewählte Form passt zum eigenen Sicherheitsbedürfnis und fördert das Sprechen.',
 'Lassen Sie Lernende wählen, ob sie ein Gespräch vorbereiten, improvisieren oder aufnehmen.',
 'Vor dem Rollenspiel «beim Arzt» schreibt sich Frau L. Stichworte auf, während Herr M. spontan loslegt – beide üben dieselbe Situation.',
 'Ermutigen Sie sicherere Lernende behutsam, auch mal die freie Form zu probieren.'),
(1, 31, 'Wahlprojekte anbieten',
 'Projekte mit gleichem Sprachfokus, aber freiem Thema verbinden Struktur und Eigeninteresse.',
 'Die Themenwahl steigert Engagement und Ausdauer über mehrere Lektionen hinweg.',
 'Bieten Sie Wahlprojekte an (Wegbeschreibung, Bewerbung, Rezept) mit gleichem Sprachfokus.',
 'Drei Projekte stehen zur Wahl. Frau N. erstellt ein Rezept aus ihrer Heimat, Herr O. eine Wegbeschreibung zum Kurs – beide üben Imperativ.',
 'Definieren Sie das gemeinsame Sprachziel klar, damit die Vielfalt nicht beliebig wird.'),
(1, 32, 'Sozialform mitbestimmen',
 'Die Sozialform der nächsten Lektion lässt sich gemeinsam aushandeln.',
 'Mitbestimmung über das Wie stärkt Verantwortung für das gemeinsame Lernen.',
 'Lassen Sie Lernende über die Sozialform der nächsten Lektion mitentscheiden.',
 'Am Ende der Stunde fragen Sie: «Nächstes Mal lieber Partner- oder Gruppenarbeit?» Die Gruppe entscheidet sich für Partnerarbeit.',
 'Wechseln Sie über die Zeit bewusst durch, damit nicht immer dieselbe Form gewählt wird.'),
(1, 33, 'Lernweg-Tagebuch',
 'Eigene Entscheidungen werden bewusst, wenn sie festgehalten werden.',
 'Das Dokumentieren fördert Reflexion und Verantwortung für den eigenen Weg.',
 'Geben Sie ein «Lernweg-Tagebuch» aus, in dem eigene Entscheidungen festgehalten werden.',
 'Frau P. notiert: «Heute habe ich die schwere Aufgabe gewählt – es war anstrengend, aber ich habe viel gelernt.»',
 'Halten Sie die Einträge kurz, sonst wird das Tagebuch zur Last statt zur Hilfe.'),
(1, 34, 'Interessengruppen bilden',
 'Lerngruppen nach Interesse arbeiten motivierter als zufällig zusammengesetzte.',
 'Gemeinsames Interesse erhöht Beteiligung und gegenseitige Unterstützung.',
 'Lassen Sie Lernende selbst Lerngruppen nach Interesse bilden.',
 'Zum Oberthema Arbeit bilden sich Gruppen: «Büro», «Baustelle», «Pflege». Herr Q. wählt Pflege, weil er dort arbeiten möchte.',
 'Behalten Sie im Blick, dass niemand ohne Gruppe zurückbleibt.'),
(1, 35, 'Wiederholungsspiel wählen',
 'Wiederholung gelingt leichter, wenn die Form selbst gewählt und freudvoll ist.',
 'Spielfreude senkt die Hemmschwelle und festigt Gelerntes nebenbei.',
 'Bieten Sie zur Wiederholung verschiedene Spiele an und lassen Sie die Gruppe wählen.',
 'Zur Auswahl stehen Bingo, Memory und ein Würfelspiel. Die Gruppe entscheidet sich für Bingo mit den Wörtern der Woche.',
 'Führen Sie jedes Spiel einmal vor, damit die Wahl auf Erfahrung beruht.'),
(1, 36, 'Alltagssituation üben',
 'Die zu übende Situation soll aus dem realen Bedarf der Lernenden stammen.',
 'Selbst gewählte Situationen sind unmittelbar nützlich und damit hoch motivierend.',
 'Lassen Sie Lernende entscheiden, welche Situation aus ihrem Alltag geübt werden soll.',
 'Frau R. wünscht sich: «Telefon mit der Schule meiner Tochter.» Daraus wird ein Rollenspiel, das alle gut gebrauchen können.',
 'Sammeln Sie mehrere Wünsche und bündeln Sie ähnliche zu einer gemeinsamen Übung.'),
(1, 37, 'Erklärvideos per QR',
 'Digitale Erklärungen können bei Bedarf und im eigenen Tempo genutzt werden.',
 'Selbstgesteuerter Zugriff erlaubt mehrfaches Ansehen ohne Druck durch die Gruppe.',
 'Stellen Sie QR-Codes zu unterschiedlichen Erklärvideos bereit, frei nach Bedarf abrufbar.',
 'An der Wand hängen QR-Codes zu Grammatikvideos. Herr S. schaut das Video zu den Artikeln zweimal, bis er es verstanden hat.',
 'Bieten Sie eine analoge Alternative für alle ohne Smartphone.'),
(1, 38, 'Tempo selbst markieren',
 'Das eigene Lerntempo wird steuerbar, wenn es sichtbar geplant wird.',
 'Die Selbsteinschätzung des Tempos stärkt realistische Planung und Selbstverantwortung.',
 'Lassen Sie Lernende ihr eigenes Lerntempo an einer Wochenübersicht markieren.',
 'Auf einer Wochenleiste markiert Frau T., wie weit sie kommen möchte. Am Freitag vergleicht sie Plan und Wirklichkeit.',
 'Betonen Sie, dass die Markierung ein Plan ist, kein Versprechen – sonst entsteht Druck.'),
(1, 39, 'Festigungsart wählen',
 'Wortschatz lässt sich über Bewegung, Bild oder Übersetzung festigen – ganz nach Typ.',
 'Die selbst gewählte Festigungsart erhöht Behaltensleistung und Lernfreude.',
 'Bieten Sie an, Wortschatz über Bewegung, Zeichnung oder Übersetzung zu festigen – freie Wahl.',
 'Zum Wortfeld Küche zeichnet Frau U. die Gegenstände, Herr V. übersetzt sie, eine dritte Gruppe spielt sie pantomimisch.',
 'Lassen Sie die Ergebnisse kurz zusammenführen, damit alle voneinander profitieren.'),
(1, 40, 'Feedbackquelle wählen',
 'Rückmeldung kann von der Kursleitung oder von Mitlernenden kommen.',
 'Die Wahl der Feedbackquelle erhöht die Bereitschaft, Rückmeldung anzunehmen.',
 'Lassen Sie Lernende selbst entscheiden, ob sie Feedback von Ihnen oder von Mitlernenden wollen.',
 'Nach dem Schreiben fragt Herr W. seine Sitznachbarin um Rückmeldung, Frau X. kommt lieber zu Ihnen.',
 'Stärken Sie die Feedbackkompetenz der Gruppe, damit Peer-Feedback hilfreich ausfällt.'),
(1, 41, 'Lernwunsch-Liste führen',
 'Eine offene, wachsende Liste hält die Lernwünsche der Gruppe lebendig.',
 'Sichtbare Wünsche zeigen, dass Anliegen aufgenommen werden, und steigern das Engagement.',
 'Geben Sie eine offene «Was-will-ich-lernen»-Liste aus, die laufend ergänzt wird.',
 'An der Pinnwand wächst die Liste Woche für Woche. Frau Y. ergänzt «Termine absagen» – Sie planen es für die Folgewoche ein.',
 'Streichen Sie Erledigtes sichtbar durch, damit Fortschritt erkennbar wird.'),
(1, 42, 'Textsorten priorisieren',
 'Textsorten aus dem eigenen Leben zeigen, was wirklich gebraucht wird.',
 'Die Priorisierung durch Lernende richtet den Kurs an realem Bedarf aus.',
 'Lassen Sie Lernende Textsorten aus ihrem Leben mitbringen und priorisieren.',
 'Die Gruppe legt mitgebrachte Texte auf den Tisch: Briefe, SMS, Plakate. Gemeinsam reihen sie, was zuerst dran kommt – die Krankenkassenbriefe gewinnen.',
 'Sorgen Sie dafür, dass auch seltene, aber wichtige Textsorten nicht untergehen.'),
(1, 43, 'Prüfungsweg wählen',
 'Auch der Nachweis von Können kann auf verschiedenen Wegen erfolgen.',
 'Die Wahl des Prüfungsformats reduziert Prüfungsangst und zeigt Können fairer.',
 'Bieten Sie mehrere Wege zum gleichen Prüfungsziel an (Portfolio, Gespräch, Test).',
 'Zum Abschluss eines Themas wählt Frau Z. ein Gespräch, Herr A. ein kleines Portfolio – beide zeigen, was sie gelernt haben.',
 'Definieren Sie für alle Wege dieselben Kriterien, damit es gerecht bleibt.'),
(1, 44, 'Pause selbst bestimmen',
 'Innerhalb eines Rahmens dürfen Lernende den richtigen Moment für eine Pause spüren.',
 'Selbstbestimmte Pausen erhalten die Konzentration und respektieren individuelle Rhythmen.',
 'Lassen Sie Lernende selbst bestimmen, wann eine Pause sinnvoll ist – innerhalb eines vereinbarten Rahmens.',
 'In einer langen Arbeitsphase legt Herr B. nach einer schwierigen Aufgabe selbst eine kurze Pause ein und arbeitet danach frischer weiter.',
 'Vereinbaren Sie klare Grenzen, damit Selbstbestimmung nicht in Dauerpause kippt.'),
(1, 45, 'Aufgabenkarten ziehen',
 'Selbstständiges Ziehen von Aufgaben fördert Eigeninitiative und Tempo.',
 'Der eigene Griff zur Karte macht den Start in eine Aufgabe verbindlicher.',
 'Stellen Sie Aufgabenkarten in einer Box bereit, aus der jede/r selbstständig zieht.',
 'Nach der Erklärung ziehen die Lernenden ihre Aufgabe selbst aus der Box. Frau C. beginnt sofort, ohne auf eine Zuteilung zu warten.',
 'Sortieren Sie die Karten nach Niveau, damit die gezogene Aufgabe passt.'),
(1, 46, 'Lernplakate gestalten',
 'Selbst gestaltete Plakate machen eigenes Wissen sichtbar und teilbar.',
 'Das Gestalten verankert Inhalte und gibt Stolz auf das eigene Produkt.',
 'Lassen Sie Lernende eigene Lernplakate gestalten und im Raum aufhängen.',
 'Eine Gruppe erstellt ein Plakat zu Wochentagen und Tageszeiten. Es hängt an der Wand und wird zur dauerhaften Lernhilfe für alle.',
 'Würdigen Sie die Plakate sichtbar, damit der Aufwand sich gelohnt anfühlt.'),
(1, 47, 'Abkürzung für Könner',
 'Wer etwas schon kann, soll nicht zur Wiederholung gezwungen werden.',
 'Eine «Ich kann das schon»-Option respektiert Vorwissen und vermeidet Langeweile.',
 'Bieten Sie zu jedem Thema eine «Ich kann das schon»-Abkürzung mit einer Anschlussaufgabe an.',
 'Beim Thema Zahlen zeigt Herr D., dass er sicher rechnet, und springt zur Anschlussaufgabe «Preise vergleichen».',
 'Halten Sie eine sinnvolle Folgeaufgabe bereit, sonst entsteht Leerlauf.'),
(1, 48, 'Niveau selbst einschätzen',
 'Lernende können einschätzen, welche Herausforderung sie sich zutrauen.',
 'Die Selbsteinschätzung stärkt Selbstvertrauen und ein realistisches Selbstbild.',
 'Lassen Sie Lernende entscheiden, welches Niveau einer Aufgabe sie sich zutrauen.',
 'Eine Aufgabe gibt es in zwei Stufen. Frau E. traut sich die schwierigere zu und ist stolz, als sie sie schafft.',
 'Ermutigen Sie zum Ausprobieren, ohne zu drängen – die Wahl bleibt frei.'),
(1, 49, 'Offene Rechercheaufträge',
 'Selbstständiges Herausfinden fördert Eigeninitiative und echte Sprachhandlung.',
 'Der freie Weg zur Lösung macht Lernende zu aktiv Suchenden statt passiv Empfangenden.',
 'Geben Sie offene Rechercheaufträge: «Finden Sie heraus, wie man hier …» mit frei wählbarem Weg.',
 'Auftrag: «Finden Sie heraus, wann die Bibliothek offen ist.» Herr F. fragt vor Ort, Frau G. schaut online – beide bringen die Antwort mit.',
 'Besprechen Sie die Wege danach, damit die Gruppe verschiedene Strategien kennenlernt.'),
(1, 50, 'Wiederholung selbst wählen',
 'Am Wochenende weiss jede/r selbst, was noch unsicher ist und Wiederholung braucht.',
 'Die selbst bestimmte Wiederholung richtet die Festigung gezielt auf echte Lücken.',
 'Lassen Sie Lernende am Ende jeder Woche selbst wählen, was nächste Woche wiederholt wird.',
 'Am Freitag sammeln Sie Wiederholungswünsche. «Die Artikel nochmal» bekommt die meisten Stimmen und startet die neue Woche.',
 'Halten Sie die Wiederholung kurz und gezielt, damit Neues nicht zu kurz kommt.')
ON CONFLICT (id) DO NOTHING;
