-- =========================================================
-- SEED: Tipps zu Item 5 (Nr. 1–50)
-- «In meinem Kurs bin ich als Lehrende/Lehrender prozessverantwortlich und schaffe die Bedingungen für das gelingende Selbstlernen der Lernenden.»
-- =========================================================
INSERT INTO spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig) VALUES
(5, 1, 'Lernumgebung vorbereiten',
 'Ermöglichungsdidaktik gestaltet Umgebungen statt Lektionen lückenlos durchzuplanen.',
 'Eine vorbereitete Umgebung lädt zum selbstständigen Arbeiten ein.',
 'Bereiten Sie Lernumgebungen vor, statt Lektionen lückenlos durchzuplanen.',
 'Statt einer Minutenplanung richten Sie vier Stationen mit Material ein. Die Gruppe arbeitet sich selbstständig durch, Sie begleiten.',
 'Eine offene Umgebung braucht klare Rahmen, sonst entsteht Orientierungslosigkeit.'),
(5, 2, 'Sich zurückhalten',
 'Selbstlernen braucht Raum, den die Leitung bewusst freilässt.',
 'Bewusste Zurückhaltung gibt Lernenden Zeit für eigenes Denken.',
 'Halten Sie sich bewusst zurück und geben Sie Lernenden Zeit zum eigenen Denken.',
 'Nach einer Frage zählen Sie innerlich bis zehn, bevor Sie helfen. In dieser Zeit findet Frau A. die Antwort selbst.',
 'Halten Sie die Stille aus – sie ist Denkzeit, kein Versagen.'),
(5, 3, 'Atmosphäre schaffen',
 'Eine sichere Atmosphäre ist Voraussetzung für mutiges Lernen.',
 'Eine freundliche Stimmung senkt Hemmschwellen und fördert Fragen.',
 'Sorgen Sie für eine ruhige, freundliche Raumatmosphäre, in der Fragen willkommen sind.',
 'Sie begrüssen jede Person mit Namen und einem Lächeln. Der Kurs beginnt warm, und auch Zurückhaltende trauen sich zu fragen.',
 'Achten Sie auf die eigene Stimmung – sie überträgt sich auf die Gruppe.'),
(5, 4, 'Vielfältiges Material',
 'Selbstständiges Schöpfen setzt eine reiche Materialbasis voraus.',
 'Vielfältiges Material erlaubt individuelle Wege und Zugänge.',
 'Stellen Sie vielfältige Materialien bereit, aus denen selbstständig geschöpft werden kann.',
 'In der Materialecke liegen Bildkarten, Texte in mehreren Stufen und Tablets. Jede Person findet etwas Passendes für sich.',
 'Sortieren Sie das Material übersichtlich, sonst wird die Fülle zur Hürde.'),
(5, 5, 'Erst beobachten',
 'Gezieltes Eingreifen setzt vorheriges Beobachten voraus.',
 'Das Beobachten zeigt, wann Hilfe wirklich nötig ist.',
 'Beobachten Sie zuerst, bevor Sie eingreifen, und greifen Sie gezielt ein.',
 'Sie gehen durch den Raum und schauen, wo es klemmt. Bei Herrn B. greifen Sie ein, bei der Nachbargruppe lassen Sie sie selbst ringen.',
 'Verwechseln Sie Beobachten nicht mit Kontrollieren – es geht ums Verstehen.'),
(5, 6, 'Offene Phasen strukturieren',
 'Freiheit braucht Struktur, damit sie nicht in Überforderung kippt.',
 'Klare Strukturen machen offene Phasen sicher und produktiv.',
 'Strukturieren Sie offene Phasen klar, damit Freiheit nicht zu Überforderung wird.',
 'Vor der freien Arbeit klären Sie: Was, wie lange, mit welchen Hilfsmitteln. Danach arbeitet die Gruppe sicher und selbstständig.',
 'Zu viel Struktur erstickt die Freiheit, zu wenig überfordert – finden Sie die Balance.'),
(5, 7, 'Aufträge präzise formulieren',
 'Selbstständiges Arbeiten gelingt nur mit klar verständlichen Aufträgen.',
 'Präzise Aufträge ermöglichen Arbeiten ohne ständige Rückfragen.',
 'Formulieren Sie Aufträge so präzise, dass selbstständiges Arbeiten möglich ist.',
 'Statt «Macht etwas zum Thema Wohnen» sagen Sie: «Schreibt zu zweit drei Sätze über eure Wohnung.» Alle wissen sofort, was zu tun ist.',
 'Prüfen Sie Aufträge auf Verständlichkeit für das tatsächliche Sprachniveau.'),
(5, 8, 'Routinen schaffen',
 'Verlässliche Abläufe geben Sicherheit und ermöglichen Selbstständigkeit.',
 'Routinen entlasten und schaffen Raum für eigenständiges Arbeiten.',
 'Schaffen Sie Routinen, die Sicherheit geben und Selbstständigkeit erlauben.',
 'Jeder Tag beginnt gleich: ankommen, Wort des Tages, Wochenplan anschauen. Die Gruppe startet selbstständig, ohne Ihre Ansage.',
 'Erklären Sie neue Routinen anfangs gut, bis sie sich eingespielt haben.'),
(5, 9, 'Redeanteil reduzieren',
 'Lernende lernen mehr, wenn sie selbst sprechen statt zuzuhören.',
 'Weniger Lehrendenrede schafft mehr Sprechzeit für die Lernenden.',
 'Reduzieren Sie Ihren Redeanteil zugunsten der Lernenden.',
 'Sie erklären kurz und geben dann die Bühne frei. In der Stunde sprechen die Lernenden mehr als Sie – genau so soll es sein.',
 'Beobachten Sie sich selbst kritisch: Wie viel reden Sie wirklich?'),
(5, 10, 'Hilfsmittel ohne Leitung',
 'Selbstständigkeit wächst, wenn Hilfsmittel ohne die Leitung nutzbar sind.',
 'Selbst nutzbare Hilfsmittel machen Lernende unabhängig.',
 'Bereiten Sie Hilfsmittel vor, die Lernende ohne Sie nutzen können (Lösungen, Modelle, QR-Codes).',
 'Sie legen Lösungsblätter und Modelltexte aus. Als Frau C. nicht weiterkommt, greift sie selbst danach, statt zu warten.',
 'Erklären Sie einmal, wie die Hilfsmittel zu nutzen sind.'),
(5, 11, 'Fehlerfreundliche Stimmung',
 'Ausprobieren gelingt nur, wo Fehler sicher sein dürfen.',
 'Eine fehlerfreundliche Stimmung fördert Mut und Beteiligung.',
 'Sorgen Sie für eine fehlerfreundliche Stimmung, in der Ausprobieren sicher ist.',
 'Als Herr D. einen Fehler macht, reagieren Sie freundlich und interessiert. Andere sehen, dass Fehler hier kein Problem sind.',
 'Achten Sie auch auf Reaktionen der Gruppe, nicht nur auf die eigene.'),
(5, 12, 'Pufferzeiten einplanen',
 'Individuelles Lerntempo braucht zeitlichen Spielraum.',
 'Pufferzeiten erlauben, dass jede/r im eigenen Takt arbeitet.',
 'Planen Sie Pufferzeiten ein, damit Lerntempo individuell sein darf.',
 'Sie planen für eine Aufgabe grosszügig Zeit ein. Frau E. wird schnell fertig und übt weiter, Herr F. braucht länger – beide kommen an.',
 'Halten Sie sinnvolle Anschlussaufgaben für Schnelle bereit.'),
(5, 13, 'Raum flexibel einrichten',
 'Verschiedene Sozialformen brauchen einen wandelbaren Raum.',
 'Ein flexibler Raum ermöglicht Einzel-, Partner- und Gruppenarbeit.',
 'Richten Sie den Raum so ein, dass verschiedene Sozialformen möglich sind.',
 'Die Tische lassen sich leicht umstellen. Für die Gruppenarbeit schiebt die Klasse sie in Minuten zu Inseln zusammen.',
 'Klären Sie das Umstellen als Routine, damit es keine Zeit frisst.'),
(5, 14, 'Lernziele transparent machen',
 'Selbststeuerung gelingt nur mit bekannten Zielen.',
 'Transparente Ziele erlauben Lernenden, sich selbst zu orientieren.',
 'Machen Sie Lernziele transparent, damit Lernende sich selbst orientieren können.',
 'Zu Beginn schreiben Sie das Tagesziel an die Tafel: «Heute können wir nach dem Weg fragen.» Alle wissen, worauf es zugeht.',
 'Formulieren Sie Ziele in einfacher, könnensorientierter Sprache.'),
(5, 15, 'Verantwortung schrittweise abgeben',
 'Selbstständigkeit entsteht durch allmähliche Übergabe von Verantwortung.',
 'Schrittweises Abgeben verhindert Überforderung und baut Vertrauen auf.',
 'Geben Sie Verantwortung schrittweise ab, statt alles auf einmal loszulassen.',
 'Zuerst übernimmt die Gruppe nur die Zeitansage, später ganze Übungsphasen. Schritt für Schritt wird sie selbstständiger.',
 'Achten Sie auf das Tempo der Gruppe, nicht auf das eigene Ideal.'),
(5, 16, 'Gestufte Hilfen vorbereiten',
 'Passende Hilfe bedeutet, das richtige Mass selbst wählen zu können.',
 'Gestufte Hilfen erlauben, nur so viel Unterstützung zu nehmen wie nötig.',
 'Bereiten Sie gestufte Hilfen vor, damit Lernende selbst das richtige Mass wählen.',
 'Zu einer Aufgabe liegen drei Hilfekarten bereit: ein Tipp, ein Beispiel, die Lösung. Herr G. nimmt nur den Tipp und schafft den Rest allein.',
 'Sortieren Sie die Hilfen klar von wenig zu viel.'),
(5, 17, 'Fragen statt Antworten',
 'Eigenes Denken wird durch Fragen angeregt, nicht durch fertige Antworten.',
 'Gegenfragen aktivieren das eigene Nachdenken der Lernenden.',
 'Stellen Sie Fragen, statt Antworten zu liefern.',
 'Als Frau H. fragt, ob ihr Satz richtig ist, fragen Sie zurück: «Was meinen Sie?» Sie prüft selbst und findet die Antwort.',
 'Achten Sie darauf, dass Ihre Fragen weiterhelfen und nicht verwirren.'),
(5, 18, 'Wege aus dem Stillstand',
 'Selbstständigkeit braucht klare Optionen für Momente des Steckenbleibens.',
 'Bekannte Auswege verhindern Frust und passives Warten.',
 'Sorgen Sie dafür, dass jede/r weiss, was bei Stillstand zu tun ist.',
 'An der Wand hängt: «Stecke ich fest? 1. nochmal lesen 2. Nachbarn fragen 3. nachschlagen.» Herr I. arbeitet die Schritte selbst ab.',
 'Üben Sie die Schritte einmal gemeinsam ein.'),
(5, 19, 'Material in mehreren Niveaus',
 'Heterogene Gruppen brauchen Material auf verschiedenen Niveaus.',
 'Mehrstufiges Material erlaubt passende Herausforderung für alle.',
 'Halten Sie Material in mehreren Niveaus bereit, ohne es vorzuschreiben.',
 'Ein Text liegt in zwei Versionen aus. Frau J. nimmt die einfachere, Herr K. die anspruchsvollere – beide arbeiten am selben Thema.',
 'Vermeiden Sie eine sichtbare Abwertung der einfacheren Stufe.'),
(5, 20, 'Reflexion fest einplanen',
 'Reflexion gehört verlässlich zum Lernprozess, nicht nur zufällig.',
 'Feste Reflexionsphasen verankern bewusstes Lernen.',
 'Planen Sie Reflexionsphasen fest ein, statt sie dem Zufall zu überlassen.',
 'Jeden Freitag gibt es zehn Minuten Rückblick. Die Gruppe ist es gewohnt und nutzt die Zeit, um den eigenen Fortschritt zu prüfen.',
 'Halten Sie die Reflexion kurz und regelmässig statt selten und lang.'),
(5, 21, 'Leisere einbeziehen',
 'Gelingendes Lernen schliesst alle ein, auch die Zurückhaltenden.',
 'Bewusste Einbindung gibt auch leiseren Lernenden Raum.',
 'Achten Sie darauf, dass leisere Lernende ebenso Raum bekommen.',
 'In der Runde achten Sie darauf, dass auch die stille Frau L. zu Wort kommt – mit einer Form, die sie nicht überfordert.',
 'Drängen Sie niemanden, sondern schaffen Sie sichere Gelegenheiten.'),
(5, 22, 'Zeitfenster fürs Selbstlernen',
 'Selbstständiges Arbeiten braucht verlässliche, geschützte Zeit.',
 'Feste Zeitfenster machen Selbstlernen zur Selbstverständlichkeit.',
 'Schaffen Sie verlässliche Zeitfenster für selbstständiges Arbeiten.',
 'Jeden Tag gibt es 20 Minuten Stillarbeit am eigenen Schwerpunkt. Die Gruppe kennt und schätzt diese feste Zeit.',
 'Schützen Sie diese Zeit vor Unterbrechungen.'),
(5, 23, 'Gruppen begleiten',
 'Gruppen brauchen Begleitung, keine Kontrolle.',
 'Begleitendes Dasein fördert Selbstständigkeit statt Abhängigkeit.',
 'Begleiten Sie Gruppen, statt sie zu kontrollieren.',
 'Sie setzen sich kurz zu einer Gruppe, hören zu und gehen weiter, ohne einzugreifen. Die Gruppe arbeitet eigenständig weiter.',
 'Widerstehen Sie dem Drang, jede Kleinigkeit zu korrigieren.'),
(5, 24, 'Klare Übergänge',
 'Wechsel zwischen Phasen gelingen mit klaren Signalen.',
 'Klare Übergänge halten den Lernfluss aufrecht.',
 'Sorgen Sie für klare Übergänge zwischen den Phasen.',
 'Mit einem vereinbarten Klangsignal beenden Sie die Gruppenarbeit. Alle wissen: Jetzt kommen wir zusammen, und der Wechsel läuft ruhig.',
 'Nutzen Sie immer dasselbe Signal, damit es verlässlich wirkt.'),
(5, 25, 'Hilfsmittel zugänglich halten',
 'Selbstständigkeit setzt jederzeit erreichbare Hilfsmittel voraus.',
 'Zugängliche Hilfsmittel ermöglichen eigenständiges Arbeiten.',
 'Stellen Sie sicher, dass Hilfsmittel jederzeit zugänglich sind.',
 'Wörterbücher und Bildkarten stehen offen im Regal. Herr M. holt sich, was er braucht, ohne zu fragen.',
 'Vereinbaren Sie, dass alles wieder an seinen Platz zurückkommt.'),
(5, 26, 'Sichtbare Pläne',
 'Orientierung entsteht durch sichtbare Tages- und Wochenpläne.',
 'Sichtbare Pläne geben Halt und ermöglichen Selbststeuerung.',
 'Geben Sie Orientierung durch sichtbare Tages- oder Wochenpläne.',
 'An der Wand hängt der Wochenplan. Frau N. schaut selbst nach, was heute drankommt, und bereitet sich vor.',
 'Halten Sie die Pläne aktuell, sonst verlieren sie ihren Wert.'),
(5, 27, 'Pausen im Gespräch',
 'Denkzeit entsteht, wenn Pausen im Gespräch ausgehalten werden.',
 'Ausgehaltene Pausen geben Raum für eigene Formulierungen.',
 'Üben Sie sich darin, Pausen im Gespräch auszuhalten.',
 'Nach Ihrer Frage warten Sie ruhig. Herr O. braucht Zeit, formuliert dann aber selbst einen ganzen Satz, statt dass Sie ihn vorsagen.',
 'Widerstehen Sie dem Reflex, jede Stille sofort zu füllen.'),
(5, 28, 'Überschaubare Wahl',
 'Wahlfreiheit wirkt nur, wenn die Optionen überschaubar bleiben.',
 'Eine begrenzte Auswahl ermöglicht echte, nicht überfordernde Entscheidungen.',
 'Bereiten Sie Wahlmöglichkeiten so vor, dass sie überschaubar bleiben.',
 'Sie bieten drei Aufgaben zur Wahl, nicht zehn. Frau P. entscheidet sich rasch und beginnt, statt von der Fülle gelähmt zu sein.',
 'Lieber wenige gute Optionen als viele verwirrende.'),
(5, 29, 'Niemanden beschämen',
 'Sicheres Lernen braucht Schutz vor Beschämung.',
 'Eine beschämungsfreie Atmosphäre erhält Lernfreude und Mut.',
 'Sorgen Sie für ein Klima, in dem niemand für Tempo oder Fehler beschämt wird.',
 'Als Herr Q. langsamer ist, machen Sie kein Thema daraus. Er arbeitet in Ruhe weiter, ohne sich schlecht zu fühlen.',
 'Achten Sie auch auf abwertende Reaktionen innerhalb der Gruppe.'),
(5, 30, 'Sich überflüssig machen',
 'Das Ziel der Begleitung ist die wachsende Selbstständigkeit der Lernenden.',
 'Wer sich überflüssig macht, hat Selbstlernen ermöglicht.',
 'Planen Sie bewusst, wann Sie sich überflüssig machen können.',
 'In der Stillarbeit haben Sie kaum etwas zu tun – die Gruppe arbeitet selbst. Sie nutzen die Zeit zum Beobachten und freuen sich darüber.',
 'Sehen Sie das nicht als Kontrollverlust, sondern als Erfolg.'),
(5, 31, 'Gegenseitige Hilfe ermöglichen',
 'Lernende sind füreinander wertvolle Ressourcen.',
 'Gegenseitige Hilfe entlastet die Leitung und stärkt die Gruppe.',
 'Schaffen Sie Gelegenheiten, in denen Lernende einander helfen.',
 'Bevor jemand zu Ihnen kommt, fragt er die Nachbarin. Frau R. erklärt Herrn S. die Uhrzeit – beide profitieren davon.',
 'Achten Sie darauf, dass Helfen freiwillig bleibt.'),
(5, 32, 'Gezielt beobachten',
 'Gute Begleitung beruht auf gezielter Beobachtung.',
 'Gezieltes Beobachten zeigt, wo Selbststeuerung gelingt und wo nicht.',
 'Beobachten Sie gezielt, wo Selbststeuerung gelingt und wo Unterstützung nötig ist.',
 'Beim Rundgang sehen Sie: Diese Gruppe läuft, jene stockt. Sie unterstützen gezielt dort, wo es wirklich nötig ist.',
 'Machen Sie sich kurze Notizen, um nichts zu übersehen.'),
(5, 33, 'Erwartungen klären',
 'Selbstständiges Arbeiten gelingt mit klar kommunizierten Erwartungen.',
 'Klare Erwartungen geben Sicherheit und Orientierung.',
 'Halten Sie Ihre Erwartungen klar und kommunizieren Sie diese.',
 'Vor der Freiarbeit sagen Sie genau, was am Ende vorliegen soll. Die Gruppe weiss, woran sie arbeitet, und bleibt fokussiert.',
 'Prüfen Sie, ob die Erwartungen wirklich verstanden wurden.'),
(5, 34, 'Material ohne Sie nutzbar',
 'Eine gute Umgebung funktioniert auch ohne ständige Anleitung.',
 'Selbsterklärendes Material macht Lernende unabhängig von der Leitung.',
 'Sorgen Sie dafür, dass Material und Raum auch ohne Sie funktionieren.',
 'Als Sie kurz den Raum verlassen, arbeitet die Gruppe ungestört weiter – alles ist so vorbereitet, dass es selbst läuft.',
 'Testen Sie Aufgaben gedanklich aus Sicht der Lernenden.'),
(5, 35, 'Eigene Steuerung reflektieren',
 'Gute Begleitung reflektiert das eigene Mass an Steuerung.',
 'Die Reflexion verbessert die Balance zwischen Lenken und Loslassen.',
 'Reflektieren Sie nach der Lektion, wo Sie zu viel oder zu wenig gesteuert haben.',
 'Nach der Stunde überlegen Sie: «Bei der Gruppenarbeit habe ich zu früh eingegriffen.» Beim nächsten Mal halten Sie sich bewusst zurück.',
 'Seien Sie dabei nachsichtig mit sich selbst – es ist ein Lernprozess.'),
(5, 36, 'Rituale fürs Starten',
 'Selbstständiges Beginnen gelingt leichter mit verlässlichen Ritualen.',
 'Startrituale ermöglichen einen selbstständigen Einstieg.',
 'Bauen Sie Rituale ein, die selbstständiges Starten erleichtern.',
 'Beim Ankommen weiss jede/r: Mappe holen, Wochenplan lesen, mit der ersten Aufgabe beginnen. Die Gruppe startet ohne Ihre Ansage.',
 'Führen Sie das Ritual geduldig ein, bis es sitzt.'),
(5, 37, 'Befähigendes Feedback',
 'Feedback soll zum Weiterarbeiten befähigen, nicht nur bewerten.',
 'Befähigendes Feedback gibt den nächsten Schritt in die Hand der Lernenden.',
 'Geben Sie Feedback, das zum Weiterarbeiten befähigt, statt nur zu bewerten.',
 'Statt «falsch» sagen Sie zu Herrn T.: «Schauen Sie die Endung an.» Er korrigiert selbst und hat etwas gelernt.',
 'Verbinden Sie Feedback immer mit einem nächsten Schritt.'),
(5, 38, 'Regeln gemeinsam tragen',
 'Regeln wirken, wenn sie von allen getragen werden.',
 'Gemeinsam getragene Regeln schaffen ein verlässliches Lernklima.',
 'Stellen Sie sicher, dass Regeln gemeinsam getragen werden.',
 'Die zu Beginn vereinbarten Regeln hängen sichtbar. Als jemand sie vergisst, erinnert die Gruppe selbst daran – nicht nur Sie.',
 'Überprüfen Sie die Regeln ab und zu gemeinsam auf Aktualität.'),
(5, 39, 'Sinn transparent machen',
 'Selbstständiges Erarbeiten gelingt besser, wenn der Sinn klar ist.',
 'Transparenz über das Warum erhöht Akzeptanz und Engagement.',
 'Schaffen Sie Transparenz darüber, warum etwas selbstständig erarbeitet wird.',
 'Sie erklären: «Wenn Sie es selbst herausfinden, behalten Sie es besser.» Frau U. versteht den Sinn und macht engagierter mit.',
 'Wiederholen Sie das Warum, bis die Haltung verinnerlicht ist.'),
(5, 40, 'Flexibel planen',
 'Prozessverantwortung heisst, auf die Gruppe reagieren zu können.',
 'Flexible Planung erlaubt das Eingehen auf aktuelle Bedürfnisse.',
 'Planen Sie flexibel genug, um auf die Gruppe reagieren zu können.',
 'Als ein Thema die Gruppe mehr beschäftigt als gedacht, bleiben Sie dabei und verschieben den Rest – Ihre Planung lässt das zu.',
 'Halten Sie ein Grundgerüst, damit Flexibilität nicht in Beliebigkeit kippt.'),
(5, 41, 'Struktur und Freiheit',
 'Gelingendes Selbstlernen lebt von der Balance aus Struktur und Freiheit.',
 'Die richtige Balance ermöglicht sicheres und selbstständiges Lernen.',
 'Sorgen Sie für eine gute Balance aus Struktur und Freiheit.',
 'Sie geben klare Aufgaben, lassen aber den Weg frei. Herr V. fühlt sich sicher geführt und doch eigenständig.',
 'Beobachten Sie, ob die Gruppe mehr Struktur oder mehr Freiheit braucht.'),
(5, 42, 'Unsicherheit aushalten',
 'Offene Prozesse bringen Unsicherheit mit sich, die auszuhalten ist.',
 'Das Aushalten von Unsicherheit gibt selbstständigen Prozessen Raum.',
 'Bereiten Sie sich darauf vor, Unsicherheit der Gruppe auszuhalten.',
 'In der offenen Phase wirkt es kurz chaotisch. Sie bleiben ruhig, und tatsächlich ordnet sich die Arbeit von selbst.',
 'Greifen Sie nicht aus eigener Nervosität zu früh ein.'),
(5, 43, 'Fortschritte sichtbar machen',
 'Selbstvertrauen wächst mit sichtbaren Fortschritten.',
 'Sichtbarer Fortschritt stärkt Motivation und Zutrauen.',
 'Machen Sie Fortschritte sichtbar, damit Selbstvertrauen wächst.',
 'Sie zeigen der Gruppe, was sie vor einem Monat noch nicht konnte. Das Staunen über den eigenen Fortschritt motiviert sichtbar.',
 'Bleiben Sie dabei konkret und ehrlich.'),
(5, 44, 'Auf Augenhöhe begleiten',
 'Ermöglichungsdidaktik begleitet auf Augenhöhe statt von oben zu belehren.',
 'Begleitung auf Augenhöhe stärkt Selbstständigkeit und Würde.',
 'Üben Sie, auf Augenhöhe zu begleiten statt von oben zu belehren.',
 'Sie setzen sich zu Frau W. und überlegen gemeinsam, statt ihr die Lösung zu diktieren. Sie fühlt sich ernst genommen.',
 'Achten Sie auf Sprache und Haltung, die nicht herablassend wirken.'),
(5, 45, 'Geschützte Räume für Fragen',
 'Manche Fragen brauchen einen geschützten, individuellen Rahmen.',
 'Geschützte Räume ermöglichen Fragen ohne Scham vor der Gruppe.',
 'Schaffen Sie geschützte Räume für individuelle Fragen.',
 'In der Stillarbeit gehen Sie herum, sodass Herr X. seine Frage leise stellen kann, ohne dass alle es hören.',
 'Signalisieren Sie, dass jede Frage willkommen ist.'),
(5, 46, 'Werkzeuge zur Selbstorganisation',
 'Selbstorganisation gelingt mit den passenden Werkzeugen.',
 'Geeignete Werkzeuge befähigen die Gruppe, sich selbst zu organisieren.',
 'Geben Sie der Gruppe Werkzeuge zur Selbstorganisation an die Hand.',
 'Sie führen einen einfachen Wochenplan und eine Aufgabenliste ein. Die Gruppe organisiert damit ihr Lernen zunehmend selbst.',
 'Erklären Sie die Werkzeuge, bis sie selbstverständlich genutzt werden.'),
(5, 47, 'Hilfe knapp halten',
 'Wirksame Hilfe ist so knapp wie möglich und so umfangreich wie nötig.',
 'Knappe Hilfe fördert Selbstständigkeit statt Abhängigkeit.',
 'Halten Sie Ihre Hilfe so knapp wie möglich und so umfangreich wie nötig.',
 'Frau Y. braucht nur einen kleinen Hinweis. Sie geben genau diesen und nicht mehr – den Rest schafft sie selbst.',
 'Widerstehen Sie der Versuchung, mehr zu erklären als gebraucht wird.'),
(5, 48, 'Klare Zeit- und Mengenangaben',
 'Offene Aufgaben brauchen klare Angaben zu Zeit und Umfang.',
 'Klare Vorgaben geben offenen Aufgaben einen sicheren Rahmen.',
 'Sorgen Sie für klare Zeit- und Mengenangaben bei offenen Aufgaben.',
 'Sie sagen: «Sie haben 15 Minuten und schreiben mindestens drei Sätze.» Herr Z. weiss genau, woran er ist, und teilt sich die Zeit ein.',
 'Passen Sie die Vorgaben realistisch an die Gruppe an.'),
(5, 49, 'Eigene Rolle reflektieren',
 'Die eigene Rolle als Begleitperson will regelmässig reflektiert sein.',
 'Die Reflexion der eigenen Rolle verbessert die Begleitung stetig.',
 'Reflektieren Sie regelmässig Ihre eigene Rolle als Begleitperson.',
 'Am Ende der Woche fragen Sie sich: «War ich heute eher Begleiter oder Lenker?» Die Antwort fliesst in die nächste Woche ein.',
 'Holen Sie sich ab und zu auch Rückmeldung von der Gruppe.'),
(5, 50, 'Vertrauen zeigen',
 'Gelingendes Selbstlernen beruht auf Vertrauen in die Lernfähigkeit.',
 'Gezeigtes Vertrauen stärkt das Zutrauen der Lernenden in sich selbst.',
 'Vertrauen Sie auf die Lernfähigkeit der Gruppe und zeigen Sie dieses Vertrauen.',
 'Sie geben eine anspruchsvolle Aufgabe mit den Worten: «Das schaffen Sie.» Die Gruppe wächst sichtlich an diesem Vertrauen.',
 'Lassen Sie das Vertrauen echt sein, nicht nur eine Floskel.')
ON CONFLICT (id) DO NOTHING;
