-- =========================================================
-- SEED: Tipps zu Item 4 (Nr. 1–50)
-- «In meinem Kurs werden Lernende darin unterstützt, die Verantwortung für ihr Lernen selbst zu übernehmen.»
-- =========================================================
INSERT INTO spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig) VALUES
(4, 1, 'Lerntagebuch einführen',
 'Verantwortung wächst, wenn Lernende ihren eigenen Prozess regelmässig festhalten.',
 'Das Führen eines Tagebuchs macht eigenes Lernen bewusst und steuerbar.',
 'Führen Sie ein persönliches Lerntagebuch ein, das regelmässig gepflegt wird.',
 'Frau A. notiert jeden Freitag drei Sätze zu ihrer Woche. Mit der Zeit erkennt sie selbst, was ihr beim Lernen hilft.',
 'Geben Sie wenige feste Leitfragen vor, damit das Tagebuch nicht zur Last wird.'),
(4, 2, 'Realistisches Ziel setzen',
 'Selbst gesetzte, erreichbare Ziele sind die Basis für eigenverantwortliches Lernen.',
 'Ein realistisches Wochenziel gibt Orientierung und schafft Erfolgserlebnisse.',
 'Lassen Sie Lernende zu Wochenbeginn ein eigenes, realistisches Ziel formulieren.',
 'Herr B. nimmt sich vor: «Diese Woche lese ich jeden Tag fünf Minuten.» Am Freitag berichtet er, dass es geklappt hat.',
 'Helfen Sie, Ziele klein zu halten, damit sie nicht von vornherein überfordern.'),
(4, 3, 'Werkzeuge statt Lösungen',
 'Wer Wege zur Lösung kennt, wird unabhängig von vorgesagten Antworten.',
 'Das Aufzeigen von Werkzeugen stärkt Selbstständigkeit und Problemlösekompetenz.',
 'Geben Sie Werkzeuge an die Hand, statt Lösungen vorzusagen («Wo könnten Sie das nachschauen?»).',
 'Als Frau C. nach einem Wort fragt, zeigen Sie aufs Wörterbuch statt zu übersetzen. Beim nächsten Mal schlägt sie selbst nach.',
 'Bleiben Sie geduldig – der eigene Weg dauert anfangs länger als die schnelle Antwort.'),
(4, 4, 'Wochen-Lernplan erstellen',
 'Eigenverantwortung zeigt sich im selbst geplanten Lernen.',
 'Ein eigener Plan strukturiert die Woche und macht Fortschritt sichtbar.',
 'Lassen Sie Lernende einen eigenen Wochen-Lernplan erstellen.',
 'Herr D. teilt sich ein: Montag Wortschatz, Mittwoch Hören, Freitag Wiederholung. Er hält seinen Plan an den Kühlschrank.',
 'Geben Sie eine einfache Vorlage, damit das Planen nicht überfordert.'),
(4, 5, 'Übung zu Hause klären',
 'Warum Üben ausserhalb des Kurses nötig ist, sollte verstanden sein.',
 'Das Verstehen des Sinns erhöht die Bereitschaft, selbst zu üben.',
 'Besprechen Sie zu Beginn, wie viel Übung ausserhalb des Kurses nötig ist – und warum.',
 'Sie erklären, dass Sprache wie ein Muskel regelmässiges Training braucht. Frau E. nimmt sich daraufhin feste Übungszeiten vor.',
 'Bleiben Sie realistisch in Bezug auf Alltag, Arbeit und Familie der Lernenden.'),
(4, 6, 'Hilfe selbst holen',
 'Lernende dürfen selbst entscheiden, wann sie Unterstützung brauchen.',
 'Selbst geholte Hilfe stärkt Eigeninitiative statt passiven Wartens.',
 'Lassen Sie Lernende selbst entscheiden, wann sie Unterstützung holen.',
 'In der Übungsphase kommt Herr F. von sich aus zu Ihnen, als er nicht weiterweiss – statt zu warten, bis Sie ihn ansprechen.',
 'Machen Sie deutlich, dass Fragen erwünscht und kein Zeichen von Schwäche ist.'),
(4, 7, 'Lernstrategien zeigen',
 'Strategien sind erlernbar und erweitern die Selbststeuerung.',
 'Das Kennenlernen mehrerer Strategien erlaubt eine bewusste eigene Wahl.',
 'Zeigen Sie Lernstrategien explizit (z.B. Vokabeln mit Bildern verknüpfen) und lassen Sie wählen.',
 'Sie stellen drei Merkstrategien vor. Frau G. probiert die Bildmethode und merkt, dass sie sich damit Wörter besser einprägt.',
 'Lassen Sie ausprobieren, statt eine Strategie als die beste vorzuschreiben.'),
(4, 8, 'Fortschritt dokumentieren',
 'Sichtbarer Fortschritt motiviert zur weiteren Eigenverantwortung.',
 'Das Dokumentieren macht eigene Entwicklung greifbar und stärkt das Zutrauen.',
 'Lassen Sie Lernende ihren Lernfortschritt sichtbar dokumentieren (Lernkurve, Mappe).',
 'Herr H. führt eine Mappe mit Datum auf jedem Blatt. Beim Zurückblättern sieht er, wie weit er gekommen ist.',
 'Bieten Sie eine einfache Form an, die ohne grossen Aufwand zu pflegen ist.'),
(4, 9, 'Mini-Ziele prüfen',
 'Kleine vereinbarte Ziele lassen sich gemeinsam überprüfen.',
 'Das Prüfen von Mini-Zielen macht Verantwortung konkret und folgenreich.',
 'Vereinbaren Sie individuelle Mini-Ziele und prüfen Sie diese später gemeinsam.',
 'Mit Frau I. vereinbaren Sie: «Bis Freitag fünf neue Wörter zum Thema Arzt.» Am Freitag zeigt sie stolz ihre Liste.',
 'Würdigen Sie auch teilweise erreichte Ziele, damit der Mut erhalten bleibt.'),
(4, 10, 'Verantwortung fürs Material',
 'Selbst für das eigene Material zu sorgen, ist gelebte Eigenverantwortung.',
 'Das Übernehmen kleiner Pflichten stärkt Selbstständigkeit im Lernalltag.',
 'Lassen Sie Lernende Verantwortung für ihr Material übernehmen (Heft, Stift, Unterlagen).',
 'Herr J. gewöhnt sich an, seine Mappe immer dabeizuhaben. Als er einmal etwas vergisst, organisiert er sich selbst Ersatz.',
 'Begleiten Sie wohlwollend, statt bei Vergessenem sofort alles zu ersetzen.'),
(4, 11, 'Hilfe-Treppe nutzen',
 'Eine gestufte Reihenfolge der Hilfe fördert das Lösen aus eigener Kraft.',
 'Die Hilfe-Treppe macht bewusst, dass vieles auch ohne die Leitung geht.',
 'Bieten Sie eine «Hilfe-Treppe» an: erst selbst, dann Partner, dann Hilfsmittel, dann Kursleitung.',
 'Bei einer Frage geht Frau K. die Treppe durch: Sie überlegt, fragt die Nachbarin, schaut nach – und braucht Sie gar nicht mehr.',
 'Hängen Sie die Treppe sichtbar auf, damit sie zur Gewohnheit wird.'),
(4, 12, 'Erinnerungssystem entwickeln',
 'Eigene Systeme für Aufgaben fördern selbstständige Organisation.',
 'Ein selbst entwickeltes System wird verlässlicher genutzt als ein vorgegebenes.',
 'Lassen Sie Lernende eigene Erinnerungssysteme für Hausaufgaben entwickeln.',
 'Herr L. stellt sich einen Handy-Wecker für die Übungszeit. Frau M. klebt sich einen Zettel an die Tür – jede/r findet das Eigene.',
 'Stellen Sie mehrere Beispiele vor, ohne ein bestimmtes System vorzuschreiben.'),
(4, 13, 'Lernen im Alltag',
 'Der Alltag steckt voller Gelegenheiten, Deutsch zu üben.',
 'Das bewusste Nutzen des Alltags macht Lernen unabhängig vom Kursraum.',
 'Sprechen Sie über Lernen ausserhalb des Kurses (Apps, Kontakte, Alltag) und ermutigen Sie dazu.',
 'Frau N. erzählt, dass sie jetzt Werbeplakate liest und unbekannte Wörter notiert. Die Gruppe sammelt weitere Alltagsideen.',
 'Greifen Sie Alltagserfahrungen wertschätzend auf, damit sie sich lohnen.'),
(4, 14, 'Hilfreiches reflektieren',
 'Wer weiss, was hilft und was bremst, kann das eigene Lernen steuern.',
 'Die Reflexion über Lernbedingungen stärkt bewusste Eigenverantwortung.',
 'Lassen Sie Lernende reflektieren, was ihnen beim Lernen hilft und was sie bremst.',
 'Herr O. erkennt: «Mit Musik kann ich nicht lernen, aber morgens früh geht es gut.» Er richtet sein Üben danach aus.',
 'Geben Sie konkrete Reflexionsfragen, sonst bleibt es zu allgemein.'),
(4, 15, 'Wahl bewusst machen',
 'Jede Wahlmöglichkeit ist auch eine Übernahme von Verantwortung.',
 'Das Bewusstmachen der Wahl stärkt das Gefühl, selbst zu steuern.',
 'Geben Sie Wahlmöglichkeiten und machen Sie die Verantwortung der Wahl bewusst.',
 'Bei der Aufgabenwahl sagen Sie: «Sie entscheiden, was Sie weiterbringt.» Frau P. wählt bewusst die schwierigere Variante.',
 'Begleiten Sie die Wahl, ohne sie heimlich doch vorzugeben.'),
(4, 16, 'Passende Hausaufgabe wählen',
 'Lernende können einschätzen, welche Übung zu ihrem Ziel passt.',
 'Die selbst gewählte Aufgabe erhöht Sinnerleben und Erledigungsquote.',
 'Lassen Sie Lernende selbst entscheiden, welche Hausaufgabe zu ihrem Ziel passt.',
 'Herr Q. will besser sprechen und wählt deshalb die Aufgabe, eine Sprachnachricht aufzunehmen, statt schriftlich zu üben.',
 'Stellen Sie sicher, dass alle Optionen das jeweilige Lernziel bedienen.'),
(4, 17, 'Fehler als Chance',
 'Eine fehlerfreundliche Haltung ist Voraussetzung für mutiges Lernen.',
 'Das Umdeuten von Fehlern fördert Eigenverantwortung statt Vermeidung.',
 'Ermutigen Sie dazu, Fehler als Lernchance zu nutzen, und benennen Sie das offen.',
 'Als Frau R. einen Fehler macht, sagen Sie: «Gut, dass wir das jetzt sehen.» Sie traut sich danach mehr zu.',
 'Leben Sie selbst einen gelassenen Umgang mit eigenen Fehlern vor.'),
(4, 18, 'Notfallplan entwickeln',
 'Auch für verpasste Lektionen lässt sich eigenverantwortlich vorsorgen.',
 'Ein eigener Plan für Fehlzeiten verhindert, dass man den Anschluss verliert.',
 'Lassen Sie Lernende einen «Notfallplan» für verpasste Lektionen entwickeln.',
 'Herr S. vereinbart mit einer Lernpartnerin, dass sie ihm bei Abwesenheit Fotos der Tafel schickt – so bleibt er dran.',
 'Unterstützen Sie beim Aufbau verlässlicher Lernpartnerschaften.'),
(4, 19, 'Sprechstunde anbieten',
 'Ein freiwilliges Unterstützungsangebot fördert Eigeninitiative.',
 'Die selbstständige Nutzung der Sprechstunde stärkt Verantwortung fürs eigene Lernen.',
 'Bieten Sie Sprechstunden an, die Lernende eigenverantwortlich nutzen.',
 'Frau T. kommt von sich aus in die Sprechstunde, um eine Bewerbung durchzugehen, die ihr wichtig ist.',
 'Machen Sie das Angebot niederschwellig und klar in Zeit und Ort.'),
(4, 20, 'Lernzeit einschätzen',
 'Realistische Selbsteinschätzung der Lernzeit ist Teil der Eigenverantwortung.',
 'Das Planen der eigenen Zeit fördert verbindliches, regelmässiges Üben.',
 'Lassen Sie Lernende ihre Lernzeit pro Woche selbst einschätzen und planen.',
 'Herr U. überlegt, wann er Zeit hat, und trägt feste Lernfenster in seinen Wochenplan ein.',
 'Helfen Sie, die geplante Zeit realistisch an den Alltag anzupassen.'),
(4, 21, 'Erfolge sichtbar machen',
 'Selbstwirksamkeit wächst, wenn eigene Erfolge wahrgenommen werden.',
 'Sichtbare kleine Erfolge stärken das Zutrauen in die eigene Lernfähigkeit.',
 'Stärken Sie Selbstwirksamkeit, indem Sie kleine eigene Erfolge sichtbar machen.',
 'Als Frau V. zum ersten Mal allein telefoniert hat, halten Sie das in der Runde fest – sie strahlt und traut sich mehr zu.',
 'Bleiben Sie konkret bei den Erfolgen, damit das Lob glaubwürdig wirkt.'),
(4, 22, 'Strategieliste anlegen',
 'Eine persönliche Sammlung hilfreicher Strategien unterstützt das Selbststeuern.',
 'Die eigene Liste macht bewusst, was beim Lernen wirklich hilft.',
 'Lassen Sie Lernende eine persönliche «Das hilft mir»-Strategieliste anlegen.',
 'Herr W. sammelt: «laut lesen», «Wörter aufschreiben», «morgens lernen». Die Liste wird sein persönlicher Werkzeugkasten.',
 'Lassen Sie die Liste mit der Zeit wachsen und sich verändern.'),
(4, 23, 'Aufgaben übergeben',
 'Verantwortung wächst, wenn die Leitung schrittweise Aufgaben abgibt.',
 'Übernommene Aufgaben fördern Selbstständigkeit der ganzen Gruppe.',
 'Übergeben Sie schrittweise Aufgaben, die früher Sie erledigt haben (Zeitansage, Material).',
 'Frau X. übernimmt die Zeitansage bei Übungen. Sie achtet zuverlässig auf die Minuten, und Sie haben den Kopf frei für anderes.',
 'Übergeben Sie schrittweise, damit niemand mit Verantwortung überfordert wird.'),
(4, 24, 'Selbst recherchieren',
 'Eigenständiges Suchen ist aktiver und nachhaltiger als fertige Information.',
 'Das Recherchieren stärkt Eigeninitiative und reale Sprachhandlung.',
 'Lassen Sie Lernende selbst recherchieren, statt alles vorzubereiten.',
 'Statt die Öffnungszeiten vorzugeben, lassen Sie Herrn Y. sie selbst herausfinden – er ruft an und bringt die Antwort mit.',
 'Geben Sie eine klare Suchaufgabe, damit das Recherchieren gelingt.'),
(4, 25, 'Was schon versucht?',
 'Vor der Hilfe lohnt der Blick auf die eigenen bisherigen Versuche.',
 'Die Frage nach dem Versuchten fördert eigenständiges Problemlösen.',
 'Fragen Sie bei Problemen zuerst: «Was haben Sie schon versucht?»',
 'Als Frau Z. nicht weiterweiss, fragen Sie zuerst nach ihrem Versuch. Beim Erzählen kommt sie selbst auf die Lösung.',
 'Stellen Sie die Frage freundlich, nicht als Prüfung.'),
(4, 26, 'Eigene Schwerpunkte setzen',
 'Lernende können Schwerpunkte für die kommende Woche selbst wählen.',
 'Selbst gesetzte Schwerpunkte lenken Energie gezielt auf das Wichtige.',
 'Lassen Sie Lernende ihre eigenen Schwerpunkte für die nächste Woche setzen.',
 'Herr A. beschliesst, sich diese Woche auf das Schreiben zu konzentrieren, weil er bald ein Formular ausfüllen muss.',
 'Helfen Sie, nicht zu viele Schwerpunkte gleichzeitig zu setzen.'),
(4, 27, 'Freiwillige Zusatzaufgaben',
 'Ein freiwilliges Mehr fördert Eigeninitiative ohne Zwang.',
 'Die freie Entscheidung über Zusatzaufgaben stärkt Verantwortung und Motivation.',
 'Bieten Sie freiwillige Zusatzaufgaben an und überlassen Sie die Entscheidung.',
 'Frau B. nimmt die freiwillige Leseaufgabe mit, weil sie Lust auf mehr hat – ganz aus eigenem Antrieb.',
 'Werten Sie das Auslassen nicht ab, damit Freiwilligkeit echt bleibt.'),
(4, 28, 'Lernort optimieren',
 'Auch der eigene Lernort zu Hause lässt sich bewusst gestalten.',
 'Das Optimieren des Lernorts fördert konzentriertes, eigenverantwortliches Üben.',
 'Lassen Sie Lernende ihren eigenen Lernort ausserhalb des Kurses beschreiben und optimieren.',
 'Herr C. erzählt, dass er am Küchentisch lernt. Gemeinsam überlegen Sie, wie er dort weniger gestört wird.',
 'Bleiben Sie realistisch – nicht alle haben viel Platz oder Ruhe zu Hause.'),
(4, 29, 'Deutsch im Alltag suchen',
 'Aktives Suchen von Sprachgelegenheiten ist gelebte Eigenverantwortung.',
 'Das bewusste Suchen erweitert das Lernen über den Kurs hinaus.',
 'Ermutigen Sie dazu, im Alltag aktiv Deutsch zu suchen, und besprechen Sie Erfahrungen.',
 'Frau D. erzählt, dass sie an der Kasse bewusst auf Deutsch fragt. Andere lassen sich anstecken und probieren es auch.',
 'Würdigen Sie auch kleine Schritte, damit der Mut wächst.'),
(4, 30, 'Korrektur selbst wählen',
 'Lernende dürfen entscheiden, welche Korrektur sie umsetzen wollen.',
 'Die eigene Entscheidung über Korrekturen stärkt Verantwortung fürs Ergebnis.',
 'Lassen Sie Lernende selbst entscheiden, welche Korrektur sie umsetzen wollen.',
 'Sie markieren mehrere Stellen im Text von Herrn E. Er wählt aus, welche zwei er heute verbessert, und nimmt sich die anderen später vor.',
 'Achten Sie darauf, dass zentrale Verständnisfehler nicht dauerhaft liegenbleiben.'),
(4, 31, 'Gruppenrollen verteilen',
 'Verantwortung in der Gruppe lässt sich von den Lernenden selbst verteilen.',
 'Das eigene Verteilen von Rollen fördert Selbstorganisation.',
 'Geben Sie Verantwortung für Gruppenaufgaben ab (Rollen selbst verteilen).',
 'Für die Gruppenarbeit klären Frau F. und ihre Gruppe selbst, wer schreibt, wer präsentiert, wer auf die Zeit achtet.',
 'Behalten Sie im Blick, dass die Rollen fair verteilt werden.'),
(4, 32, 'Stärken einsetzen',
 'Eigene Stärken zu kennen und zu nutzen, stärkt das Selbstvertrauen.',
 'Das bewusste Einsetzen von Stärken fördert aktive Beteiligung.',
 'Lassen Sie Lernende ihre Stärken benennen und gezielt einsetzen.',
 'Herr G. zeichnet gern und gut. Bei der Gruppenarbeit übernimmt er die Plakatgestaltung und bringt seine Stärke ein.',
 'Achten Sie darauf, dass auch an Schwächeren gearbeitet wird, nicht nur an Stärken.'),
(4, 33, 'An mir oder Umständen?',
 'Die Unterscheidung zwischen Eigenanteil und Umständen schärft die Selbststeuerung.',
 'Diese Reflexion fördert einen realistischen, nicht selbstabwertenden Blick.',
 'Bieten Sie eine Wochenreflexion mit der Frage «Was lag an mir, was an den Umständen?» an.',
 'Frau H. erkennt: «Die schwierige Woche lag an der Arbeit, nicht an mir.» Das nimmt ihr unnötigen Druck.',
 'Achten Sie darauf, dass die Frage nicht in Selbstvorwürfe kippt.'),
(4, 34, 'Eigene Konsequenzen ziehen',
 'Aus Lernerfahrungen lassen sich eigene nächste Schritte ableiten.',
 'Selbst gezogene Konsequenzen sind verbindlicher als vorgegebene Ratschläge.',
 'Lassen Sie Lernende eigene Konsequenzen aus Lernerfahrungen ableiten.',
 'Herr I. stellt fest, dass er zu spät mit dem Üben begann. Er beschliesst selbst, künftig früher in der Woche anzufangen.',
 'Begleiten Sie das Ableiten mit Fragen, statt die Konsequenz vorzugeben.'),
(4, 35, 'Fragen mitnehmen',
 'Offene Fragen können eigenverantwortlich nach Hause genommen und geklärt werden.',
 'Das selbstständige Klären offener Fragen fördert Eigeninitiative.',
 'Ermutigen Sie dazu, eigene Fragen mit nach Hause zu nehmen und selbst zu klären.',
 'Frau J. nimmt eine offene Frage zur Krankenkasse mit, fragt zu Hause nach und berichtet am nächsten Tag von ihrer Lösung.',
 'Bieten Sie an, beim Klären zu helfen, wenn es allein nicht gelingt.'),
(4, 36, 'Persönliches Wörterbuch pflegen',
 'Ein eigenes Wörterbuch eigenverantwortlich zu führen, fördert Selbststeuerung.',
 'Die regelmässige Pflege verankert Wortschatz und schafft ein eigenes Werk.',
 'Lassen Sie Lernende ein persönliches Wörterbuch eigenverantwortlich pflegen.',
 'Herr K. trägt jeden Tag selbst neue Wörter ein, ohne dass Sie ihn daran erinnern müssen. Sein Heft wird immer voller.',
 'Geben Sie zu Beginn eine klare Struktur, damit die Pflege gelingt.'),
(4, 37, 'Begrüssung übernehmen',
 'Kleine wiederkehrende Aufgaben sind eine niederschwellige Verantwortung.',
 'Das Übernehmen der Begrüssung stärkt Zugehörigkeit und Selbstständigkeit.',
 'Übertragen Sie Verantwortung für die Begrüssung neuer Teilnehmender.',
 'Frau L. begrüsst neue Teilnehmende, zeigt ihnen den Raum und erklärt die Abläufe – auf Deutsch und mit Stolz.',
 'Unterstützen Sie anfangs, damit sich niemand mit der Aufgabe allein gelassen fühlt.'),
(4, 38, 'Pause vom Schwierigen',
 'Lernende dürfen selbst spüren, wann eine Pause vom Schweren guttut.',
 'Das selbst bestimmte Innehalten erhält Motivation und Konzentration.',
 'Lassen Sie Lernende selbst entscheiden, wann sie eine Pause vom Schwierigen brauchen.',
 'Beim kniffligen Thema legt Herr M. kurz eine leichtere Aufgabe ein und kehrt danach mit frischem Kopf zum Schwierigen zurück.',
 'Vereinbaren Sie, dass das Schwierige danach wieder aufgegriffen wird.'),
(4, 39, 'Feedback nach vorn',
 'Rückmeldung wirkt am stärksten, wenn der nächste Schritt bei den Lernenden liegt.',
 'Handlungsorientiertes Feedback fördert Eigenverantwortung statt Abhängigkeit.',
 'Geben Sie Feedback so, dass die nächste Handlung bei den Lernenden liegt.',
 'Statt nur Fehler zu markieren, sagen Sie zu Frau N.: «Schauen Sie die Verbstellung nochmal an.» Sie korrigiert selbst.',
 'Halten Sie das Feedback konkret genug, damit der nächste Schritt klar ist.'),
(4, 40, 'Fortschritt berichten',
 'Den eigenen Fortschritt zu berichten, macht ihn bewusst und verbindlich.',
 'Das Berichten an Lernpartner stärkt Reflexion und Verantwortung.',
 'Lassen Sie Lernende ihre Lernfortschritte einer Lernpartnerin oder einem Lernpartner berichten.',
 'Herr O. erzählt seiner Lernpartnerin, was er diese Woche geschafft hat. Beim Erzählen wird ihm selbst klar, wie viel er gelernt hat.',
 'Sorgen Sie für eine wertschätzende Gesprächsform ohne Vergleichsdruck.'),
(4, 41, 'Material selbst herstellen',
 'Selbst gemachtes Lernmaterial fördert aktive Auseinandersetzung.',
 'Das Herstellen von Karten und Plakaten verankert Inhalte besonders tief.',
 'Bieten Sie an, eigene Lernmaterialien herzustellen (Karten, Plakate).',
 'Frau P. bastelt sich Bildkarten zum Thema Küche. Beim Herstellen prägt sie sich die Wörter schon ein.',
 'Stellen Sie einfaches Material bereit, damit das Herstellen niederschwellig bleibt.'),
(4, 42, 'Ziele sichtbar festhalten',
 'Sichtbare Ziele erinnern täglich an die eigene Verantwortung.',
 'Das Festhalten an sichtbarer Stelle hält Ziele präsent und verbindlich.',
 'Lassen Sie Lernende ihre Ziele an einer sichtbaren Stelle festhalten.',
 'Herr Q. schreibt sein Wochenziel auf eine Karte am Mappendeckel. Jedes Mal beim Öffnen erinnert es ihn daran.',
 'Halten Sie die Ziele kurz, damit sie auf einen Blick erfassbar sind.'),
(4, 43, 'Selbstkorrektur fördern',
 'Wer zuerst selbst korrigiert, übernimmt Verantwortung für das eigene Produkt.',
 'Die Selbstkorrektur vor dem Eingreifen schult Genauigkeit und Selbstständigkeit.',
 'Ermutigen Sie zur Selbstkorrektur, bevor Sie eingreifen.',
 'Bevor Sie etwas sagen, geben Sie Frau R. die Gelegenheit, ihren Satz nochmal anzuschauen. Sie findet den Fehler selbst.',
 'Geben Sie ausreichend Zeit, damit die Selbstkorrektur gelingen kann.'),
(4, 44, 'Lerngelegenheiten finden',
 'Der eigene Tagesablauf enthält viele ungenutzte Lerngelegenheiten.',
 'Das Absuchen des Alltags macht eigenverantwortliches Lernen alltagstauglich.',
 'Lassen Sie Lernende ihren Tagesablauf nach Lerngelegenheiten absuchen.',
 'Herr S. entdeckt, dass er beim Warten auf den Bus Wörter wiederholen kann. Aus toter Zeit wird Lernzeit.',
 'Sammeln Sie Ideen gemeinsam, damit alle voneinander profitieren.'),
(4, 45, 'Kursritual verantworten',
 'Ein eigenes kleines Ritual zu verantworten, stärkt die Beteiligung.',
 'Das Übernehmen eines Rituals fördert Verantwortung und Regelmässigkeit.',
 'Bieten Sie Verantwortung für ein kleines Kursritual an (z.B. Wort des Tages).',
 'Frau T. wählt jeden Morgen ein «Wort des Tages» und stellt es kurz vor. Die Gruppe freut sich auf ihren Beitrag.',
 'Wechseln Sie die Verantwortung ab, damit mehrere die Chance bekommen.'),
(4, 46, 'Hilfsmittel selbst wählen',
 'Lernende können entscheiden, welche App oder welches Hilfsmittel ihnen hilft.',
 'Die eigene Wahl der Werkzeuge fördert selbstständiges, passendes Lernen.',
 'Lassen Sie Lernende selbst entscheiden, welche App oder welches Hilfsmittel sie nutzen.',
 'Herr U. probiert zwei Vokabel-Apps und bleibt bei der, die ihm liegt. Frau V. zieht Karteikarten vor – beide üben so am liebsten.',
 'Geben Sie einen kurzen Überblick, damit die Wahl informiert getroffen wird.'),
(4, 47, 'Prioritäten setzen',
 'Das Setzen von Prioritäten ist eine Kernkompetenz des Selbststeuerns.',
 'Das Bewusstmachen des Wichtigsten lenkt begrenzte Lernzeit sinnvoll.',
 'Fördern Sie das Setzen von Prioritäten («Was ist diese Woche am wichtigsten?»).',
 'Frau W. hat wenig Zeit und entscheidet: Diese Woche zählt nur das Telefonieren fürs Vorstellungsgespräch. Der Rest wartet.',
 'Helfen Sie, realistische Prioritäten zu setzen, statt alles zugleich zu wollen.'),
(4, 48, 'Geschafft-Heft führen',
 'Das Festhalten von Erreichtem stärkt das Vertrauen in die eigene Kraft.',
 'Ein Heft voller Erfolge motiviert, weiter Verantwortung zu übernehmen.',
 'Lassen Sie Lernende ihre eigenen Erfolge in einem «Geschafft»-Heft festhalten.',
 'Herr X. notiert: «Heute habe ich allein einen Termin gemacht.» Beim Durchblättern sieht er, wie vieles er schon geschafft hat.',
 'Ermutigen Sie auch dazu, kleine Erfolge einzutragen.'),
(4, 49, 'Zeitkontrolle übergeben',
 'Die Verantwortung für die Zeit kann zunehmend bei der Gruppe liegen.',
 'Die übernommene Zeitkontrolle stärkt Selbstorganisation und Eigenverantwortung.',
 'Übertragen Sie zunehmend die Zeitkontrolle bei Aufgaben an die Gruppe.',
 'Frau Y. behält bei der Gruppenarbeit die Zeit im Blick und sagt rechtzeitig Bescheid. Die Gruppe organisiert sich selbst.',
 'Geben Sie der Gruppe ein sichtbares Hilfsmittel wie eine Uhr oder einen Timer.'),
(4, 50, 'Was tun Sie diese Woche?',
 'Eine wiederkehrende Schlussfrage hält die Eigenverantwortung lebendig.',
 'Die regelmässige Frage macht das Üben ausserhalb des Kurses verbindlich.',
 'Schliessen Sie regelmässig mit der Frage: «Was tun Sie diese Woche für Ihr Deutsch?»',
 'Am Freitag sagt jede Person einen konkreten Vorsatz. Herr Z.: «Ich rede mit meinem Nachbarn auf Deutsch.» Nächste Woche wird nachgefragt.',
 'Knüpfen Sie in der Folgewoche sichtbar an die Vorsätze an, damit sie zählen.')
ON CONFLICT (id) DO NOTHING;
