-- =========================================================
-- SEED: Tipps zu Item 3 (Nr. 1–50)
-- «In meinem Kurs gestalten Lernende Ziele, Prozesse und Lernbedingungen mit.»
-- =========================================================
INSERT INTO spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig) VALUES
(3, 1, 'Gruppenregeln vereinbaren',
 'Regeln werden getragen, wenn sie gemeinsam statt von oben festgelegt werden.',
 'Mitgestaltete Regeln erhöhen die Bereitschaft, sich an sie zu halten.',
 'Vereinbaren Sie zu Kursbeginn gemeinsam Gruppenregeln und halten Sie diese sichtbar fest.',
 'Die Gruppe sammelt Wünsche fürs Miteinander. «Wir lassen uns ausreden» wird beschlossen und hängt fortan an der Wand.',
 'Formulieren Sie die Regeln positiv und in einfacher Sprache, damit alle sie verstehen.'),
(3, 2, 'Pausenzeit mitbestimmen',
 'Auch kleine Entscheidungen wie die Pause können in der Gruppe liegen.',
 'Mitbestimmung über den Ablauf stärkt das Gefühl von Selbstwirksamkeit.',
 'Lassen Sie die Gruppe entscheiden, wann die Pause stattfindet.',
 'Statt fixer Pause fragen Sie: «Jetzt oder nach der Übung?» Die Gruppe will durcharbeiten und dann länger Pause machen.',
 'Halten Sie einen Rahmen ein, damit die Pause nicht unendlich verschoben wird.'),
(3, 3, 'Lernziele bündeln',
 'Ein Kursplan wird tragfähig, wenn er aus den Zielen der Teilnehmenden entsteht.',
 'Selbst eingebrachte Ziele erhöhen Identifikation mit dem gemeinsamen Plan.',
 'Sammeln Sie zu Semesterstart Lernziele der Teilnehmenden und bündeln Sie diese zu einem Kursplan.',
 'Auf Zetteln stehen Wünsche wie «Arbeit finden» und «mit Ämtern sprechen». Sie clustern sie und machen daraus die Themen des Semesters.',
 'Machen Sie sichtbar, welcher Wunsch wo im Plan landet, damit sich alle wiederfinden.'),
(3, 4, 'Sitzordnung mitgestalten',
 'Der Raum gehört auch den Lernenden – die Anordnung darf mitbestimmt werden.',
 'Eine selbst gewählte Sitzordnung fördert Wohlbefinden und Beteiligung.',
 'Lassen Sie Lernende über die Sitzordnung mitbestimmen (Stuhlkreis, Tische, Ecken).',
 'Für die Gesprächsrunde schlägt Frau A. einen Stuhlkreis vor. Die Gruppe probiert es und bleibt dabei, weil alle sich besser sehen.',
 'Sorgen Sie dafür, dass die gewählte Ordnung zur Aufgabe passt.'),
(3, 5, 'Behalten oder ändern',
 'Laufende Rückmeldung hält den Kurs anpassbar an die Bedürfnisse der Gruppe.',
 'Die Frage nach Behalten und Ändern gibt Lernenden echte Gestaltungsmacht.',
 'Fragen Sie regelmässig: «Was soll bleiben, was sollen wir ändern?»',
 'Am Monatsende sagt Herr B.: «Die Spiele sind gut, aber wir brauchen mehr Schreiben.» Sie passen die Folgewochen an.',
 'Setzen Sie sichtbar mindestens einen Änderungswunsch um, sonst verpufft die Frage.'),
(3, 6, 'Wochenübersicht anpassen',
 'Ein gemeinsamer Plan darf lebendig bleiben und sich mit der Gruppe verändern.',
 'Das gemeinsame Anpassen schafft Orientierung und Verantwortung zugleich.',
 'Erstellen Sie gemeinsam eine Wochenübersicht und passen Sie sie laufend an.',
 'Die Übersicht hängt an der Wand. Als ein Thema mehr Zeit braucht, verschiebt die Gruppe gemeinsam den Rest.',
 'Halten Sie die Übersicht einfach und sichtbar, damit sie wirklich genutzt wird.'),
(3, 7, 'Übungssituation vorschlagen',
 'Lernende wissen am besten, welche Alltagssituation als Nächstes ansteht.',
 'Selbst vorgeschlagene Situationen sind unmittelbar relevant und motivierend.',
 'Lassen Sie Lernende vorschlagen, welche Alltagssituation als Nächstes geübt wird.',
 'Frau C. schlägt «Termin beim Amt absagen» vor, weil sie das diese Woche braucht. Daraus wird die nächste Übung.',
 'Sammeln Sie mehrere Vorschläge und bündeln Sie ähnliche zu einer Übung.'),
(3, 8, 'Wünsche-Wand führen',
 'Eine sichtbare Wand sammelt Themen- und Methodenwünsche fortlaufend.',
 'Die Wand zeigt, dass Anliegen aufgenommen werden, und lädt zum Mitgestalten ein.',
 'Bieten Sie eine «Wünsche-Wand» an, auf der Themen und Methoden gesammelt werden.',
 'An der Wand sammeln sich Zettel: «mehr Sprechen», «Thema Wohnungssuche». Sie greifen die häufigsten Wünsche in der Planung auf.',
 'Räumen Sie Erledigtes sichtbar ab, damit die Wand aktuell bleibt.'),
(3, 9, 'Tempo abstimmen',
 'Das Lerntempo der Gruppe lässt sich gemeinsam aushandeln.',
 'Mitbestimmung über das Tempo verhindert Über- und Unterforderung.',
 'Lassen Sie die Gruppe über das Tempo abstimmen («Brauchen wir mehr Zeit für …?»).',
 'Bei den Artikeln fragt Herr D. nach mehr Übung. Eine kurze Abstimmung zeigt: Die Mehrheit will noch eine Lektion dazu.',
 'Achten Sie darauf, dass auch Schnellere sinnvoll beschäftigt bleiben.'),
(3, 10, 'Umgang mit Verspätung',
 'Gemeinsame Vereinbarungen wirken stärker als verordnete Regeln.',
 'Gemeinsam vereinbarte Lösungen werden eher mitgetragen.',
 'Vereinbaren Sie gemeinsam, wie mit Verspätungen und Abwesenheiten umgegangen wird.',
 'Die Gruppe beschliesst: Wer fehlt, fragt eine Lernpartnerin nach dem Stoff. So bleibt niemand zurück, ohne dass Sie alles wiederholen.',
 'Bleiben Sie wohlwollend – viele Verspätungen haben gute Gründe wie Kinder oder Arbeit.'),
(3, 11, 'Verantwortlichkeiten übernehmen',
 'Geteilte Verantwortung macht den Kurs zur gemeinsamen Sache.',
 'Übernommene Ämter stärken Zugehörigkeit und Selbstständigkeit.',
 'Lassen Sie Lernende Verantwortlichkeiten übernehmen (Material, Tafel, Zeit, Begrüssung).',
 'Frau E. übernimmt das Austeilen der Mappen, Herr F. achtet auf die Zeit. Der Kurs läuft, ohne dass Sie alles selbst steuern.',
 'Wechseln Sie die Ämter regelmässig, damit alle einmal drankommen.'),
(3, 12, 'Lernort gemeinsam planen',
 'Lernen findet auch ausserhalb des Kursraums statt und kann mitgeplant werden.',
 'Ein gemeinsam geplanter Ausflug verbindet Sprache mit echtem Erleben.',
 'Planen Sie gemeinsam einen Ausflug oder Lernort ausserhalb des Kursraums.',
 'Die Gruppe entscheidet sich für einen Besuch in der Bibliothek. Gemeinsam überlegen sie, welche Fragen sie dort stellen wollen.',
 'Klären Sie Kosten und Erreichbarkeit vorab, damit niemand ausgeschlossen wird.'),
(3, 13, 'Wiederholen oder abschliessen',
 'Die Gruppe kann mitentscheiden, wann ein Thema genug geübt ist.',
 'Das gemeinsame Entscheiden stärkt das Gespür für den eigenen Lernstand.',
 'Lassen Sie die Gruppe entscheiden, ob ein Thema wiederholt oder abgeschlossen wird.',
 'Nach dem Thema Uhrzeit fragen Sie: «Sitzt das, oder nochmal?» Die Gruppe will eine kurze Wiederholung und dann weiter.',
 'Bieten Sie Unsicheren eine Extra-Übung, auch wenn die Mehrheit abschliessen will.'),
(3, 14, 'Fehlerkultur vereinbaren',
 'Wie mit Fehlern umgegangen wird, prägt die Sicherheit im Kurs.',
 'Eine gemeinsam vereinbarte Fehlerkultur senkt die Hemmung zu sprechen.',
 'Fragen Sie nach dem bevorzugten Umgang mit Fehlern und vereinbaren Sie eine Fehlerkultur.',
 'Die Gruppe einigt sich: Fehler sind normal, wir lachen niemanden aus. Danach melden sich auch zurückhaltende Lernende öfter.',
 'Leben Sie die vereinbarte Haltung selbst vor, sonst bleibt sie wirkungslos.'),
(3, 15, 'Gemeinsames Kursziel',
 'Ein geteiltes Ziel gibt dem Kurs eine verbindende Richtung.',
 'Das gemeinsame Ziel schafft Zusammenhalt und Motivation über Wochen.',
 'Lassen Sie Lernende ein gemeinsames Kursziel formulieren («Bis zum Sommer können wir …»).',
 'Die Gruppe formuliert: «Bis zum Sommer können wir alle ein Telefongespräch führen.» Das Ziel hängt sichtbar im Raum.',
 'Halten Sie das Ziel erreichbar, damit es am Ende ein Erfolgserlebnis wird.'),
(3, 16, 'Themenreihenfolge ordnen',
 'Die Reihenfolge der Themen muss nicht starr vorgegeben sein.',
 'Gemeinsames Ordnen richtet den Kurs an aktuellen Bedürfnissen aus.',
 'Bieten Sie an, die Reihenfolge der Themen gemeinsam neu zu ordnen.',
 'Vor den Ferien zieht die Gruppe das Thema «Reisen und Bahn» vor, weil viele wegfahren – die übrigen Themen rücken nach.',
 'Stellen Sie sicher, dass aufbauende Themen in sinnvoller Reihenfolge bleiben.'),
(3, 17, 'Wiederholungsform wählen',
 'Wie wiederholt wird, kann die Gruppe zu Wochenbeginn mitbestimmen.',
 'Die selbst gewählte Form macht Wiederholung abwechslungsreicher und akzeptierter.',
 'Lassen Sie Lernende über die Form der Wiederholung am Wochenanfang entscheiden.',
 'Am Montag wählt die Gruppe ein Quiz statt eines Arbeitsblatts, um den Stoff der Vorwoche aufzufrischen.',
 'Variieren Sie über die Zeit, damit nicht immer dieselbe Form gewählt wird.'),
(3, 18, 'Kursrat einrichten',
 'Eine feste Runde für Anliegen gibt Mitbestimmung einen verlässlichen Ort.',
 'Der regelmässige Kursrat macht Beteiligung zur Selbstverständlichkeit.',
 'Richten Sie eine regelmässige «Kursrat»-Runde für Anliegen und Vorschläge ein.',
 'Jeden Freitag gibt es zehn Minuten Kursrat. Herr G. bringt ein, dass der Raum zu warm ist – gemeinsam findet sich eine Lösung.',
 'Greifen Sie die Anliegen sichtbar auf, sonst verliert der Kursrat an Sinn.'),
(3, 19, 'Bewertungskriterien festlegen',
 'Wer Kriterien mitbestimmt, versteht sie besser und akzeptiert sie eher.',
 'Gemeinsam festgelegte Kriterien machen Bewertung transparent und fair.',
 'Lassen Sie die Gruppe gemeinsam die Bewertungskriterien für ein Projekt festlegen.',
 'Für die Projektpräsentation einigt sich die Gruppe: laut und deutlich, vollständig, freundlich. Danach wissen alle, worauf es ankommt.',
 'Halten Sie die Kriterien einfach und beobachtbar.'),
(3, 20, 'Hilfsmittel einrichten',
 'Der Lernraum lässt sich mit den gewünschten Hilfsmitteln gemeinsam ausstatten.',
 'Selbst gewählte Hilfsmittel werden eher genutzt und als hilfreich erlebt.',
 'Fragen Sie, welche Hilfsmittel im Raum gewünscht sind, und richten Sie diese ein.',
 'Die Gruppe wünscht sich Wörterbücher und eine Wortschatzwand. Beides wird eingerichtet und ab dann rege genutzt.',
 'Prüfen Sie, was machbar ist, und kommunizieren Sie offen, was nicht geht.'),
(3, 21, 'Hausaufgabenmenge aushandeln',
 'Die sinnvolle Menge an Übung lässt sich mit der Gruppe besprechen.',
 'Mitbestimmte Hausaufgaben werden eher erledigt, weil sie realistisch sind.',
 'Lassen Sie Lernende entscheiden, wie viel Hausaufgabe sinnvoll ist.',
 'Herr H. erklärt, dass er wenig Zeit hat. Die Gruppe einigt sich auf eine kleinere, dafür regelmässige Aufgabe.',
 'Sorgen Sie dafür, dass die Menge trotzdem zum Lernziel reicht.'),
(3, 22, 'Tempo-Signale vereinbaren',
 'Verständigung übers Tempo gelingt mit einfachen, vereinbarten Signalen.',
 'Vereinbarte Signale geben Lernenden eine Stimme, ohne lange erklären zu müssen.',
 'Vereinbaren Sie gemeinsam Signale für «zu schnell» und «zu langsam».',
 'Die Gruppe legt fest: flache Hand heisst «zu schnell». Als Sie zu rasch erklären, hebt Frau I. die Hand und Sie verlangsamen.',
 'Reagieren Sie zuverlässig auf die Signale, sonst werden sie nicht benutzt.'),
(3, 23, 'Glossar mitgestalten',
 'Ein gemeinsames Wörterverzeichnis wächst mit der Gruppe und gehört ihr.',
 'Das Mitgestalten verankert Wortschatz und schafft ein gemeinsames Werk.',
 'Lassen Sie die Gruppe ein gemeinsames Wörterbuch oder Glossar mitgestalten.',
 'An der Wand wächst ein Glossar. Jede Woche ergänzen Lernende neue wichtige Wörter mit Beispielsatz.',
 'Klären Sie, wer was einträgt, damit das Glossar verlässlich bleibt.'),
(3, 24, 'Lektion mitmoderieren',
 'Teile der Lektion können von Lernenden selbst geleitet werden.',
 'Das Moderieren stärkt Sprechkompetenz, Selbstvertrauen und Verantwortung.',
 'Bieten Sie an, einen Teil der Lektion von Lernenden moderieren zu lassen.',
 'Herr J. leitet die morgendliche Wiederholungsrunde. Er stellt die Fragen, die Gruppe antwortet – Sie halten sich bewusst zurück.',
 'Bereiten Sie die moderierende Person kurz vor, damit sie sich sicher fühlt.'),
(3, 25, 'Rollenspielthemen bestimmen',
 'Die Themen für Rollenspiele kennen die Lernenden aus ihrem Alltag am besten.',
 'Selbst bestimmte Themen machen Rollenspiele relevant und lebendig.',
 'Lassen Sie Lernende die Themen für Rollenspiele selbst bestimmen.',
 'Frau K. wünscht sich das Rollenspiel «Reklamation im Geschäft», weil sie genau das bald braucht. Die Gruppe spielt es durch.',
 'Sammeln Sie Themen, die mehrere brauchen, damit das Rollenspiel breit nützt.'),
(3, 26, 'Feedback sichtbar nutzen',
 'Regelmässiges Feedback wirkt nur, wenn der Kurs sich daran anpasst.',
 'Sichtbare Anpassung zeigt, dass Mitgestaltung tatsächlich etwas bewirkt.',
 'Sammeln Sie monatlich Feedback und passen Sie den Kurs sichtbar daran an.',
 'Nach der Feedbackrunde sagen Sie: «Sie wollten mehr Sprechen – ab jetzt starten wir jeden Tag mit einer Sprechübung.»',
 'Benennen Sie offen, was Sie nicht ändern können, und begründen Sie es.'),
(3, 27, 'Lernatmosphäre wählen',
 'Ob mit Musik, Bewegung oder Stille gelernt wird, kann die Gruppe mitbestimmen.',
 'Die gewählte Atmosphäre steigert Wohlbefinden und Konzentration.',
 'Lassen Sie die Gruppe entscheiden, ob mit Musik, Bewegung oder Stille gelernt wird.',
 'Für die Stillarbeit wünscht sich die Gruppe leise Musik. Sie probieren es, und die meisten arbeiten konzentrierter.',
 'Achten Sie darauf, dass die Wahl niemanden beim Lernen stört.'),
(3, 28, 'Handynutzung regeln',
 'Klare, gemeinsame Vereinbarungen zum Handy verhindern Konflikte.',
 'Eine mitgetragene Regelung wird eher eingehalten als ein Verbot.',
 'Vereinbaren Sie gemeinsam, wie die Handynutzung im Kurs gehandhabt wird.',
 'Die Gruppe beschliesst: Handys als Wörterbuch ja, fürs Private in der Pause. Alle tragen die Regel mit.',
 'Erlauben Sie das Handy bewusst als Lernwerkzeug, nicht nur als Störfaktor.'),
(3, 29, 'Plan B entwickeln',
 'Auch für schwierige Tage lässt sich gemeinsam vorsorgen.',
 'Ein mitentwickelter Plan B gibt Sicherheit, wenn etwas nicht wie geplant läuft.',
 'Lassen Sie Lernende einen «Plan B» für schwierige Tage mitentwickeln.',
 'Für Tage mit wenig Energie vereinbart die Gruppe ein ruhiges Programm: Wiederholungsspiele statt neuem Stoff.',
 'Nutzen Sie den Plan B bewusst, damit er nicht in Vergessenheit gerät.'),
(3, 30, 'Material mitwählen',
 'Lehrmaterial wird besser angenommen, wenn die Gruppe mitentscheidet.',
 'Mitgewähltes Material erhöht Akzeptanz und Nutzung.',
 'Bieten Sie eine Mitsprache bei der Auswahl von Lehrmaterial an (Buch, Kopien, App).',
 'Sie zeigen zwei mögliche Übungsformate. Die Gruppe wählt die App, weil viele zu Hause damit weiterüben können.',
 'Bieten Sie nur Optionen an, die didaktisch wirklich geeignet sind.'),
(3, 31, 'Raum mitgestalten',
 'Ein Raum, den man mitgestaltet, wird zum eigenen Lernort.',
 'Die Mitgestaltung schafft Wohlbefinden und Identifikation.',
 'Lassen Sie Lernende den Raum mitgestalten (Plakate, Pflanzen, Lernecken).',
 'Die Gruppe hängt eigene Wortplakate auf und stellt eine Pflanze ans Fenster. Der Raum fühlt sich nun an wie «ihrer».',
 'Klären Sie mit der Institution, was erlaubt ist.'),
(3, 32, 'Anfangs- und Schlussrituale',
 'Wiederkehrende Rituale geben dem Kurs Struktur und Geborgenheit.',
 'Gemeinsam gewählte Rituale stärken Zugehörigkeit und Verlässlichkeit.',
 'Vereinbaren Sie gemeinsam Rituale für Anfang und Ende der Lektion.',
 'Die Gruppe beschliesst, jeden Tag mit «einem schönen Moment von gestern» zu starten. Das Ritual wird zum verbindenden Auftakt.',
 'Halten Sie die Rituale kurz, damit sie nicht zur Pflichtübung werden.'),
(3, 33, 'Feste gemeinsam nutzen',
 'Anlässe und Feste bieten reichen Sprech- und Begegnungsanlass.',
 'Die gemeinsame Gestaltung verbindet Sprachlernen mit Gemeinschaft.',
 'Lassen Sie die Gruppe entscheiden, welche Feste oder Anlässe gemeinsam genutzt werden.',
 'Die Gruppe möchte ein kleines Sommerfest mit Essen aus verschiedenen Ländern. Beim Planen wird viel Deutsch gesprochen.',
 'Achten Sie auf eine inklusive Gestaltung, die keine Tradition ausschliesst.'),
(3, 34, 'Aktuelle Anliegen aufnehmen',
 'Jede Woche bringt neue Anliegen, die den Kurs prägen dürfen.',
 'Das Aufnehmen aktueller Themen hält den Kurs lebensnah.',
 'Fragen Sie zu Beginn jeder Woche nach aktuellen Anliegen und integrieren Sie diese.',
 'Am Montag erzählt Frau L. von einem Brief vom Amt. Sie machen daraus spontan das Thema der ersten Lektion.',
 'Halten Sie etwas Planungsspielraum frei, damit Anliegen wirklich Platz haben.'),
(3, 35, 'Erfolge feiern',
 'Wie Erfolge gefeiert werden, darf die Gruppe selbst bestimmen.',
 'Selbst gewählte Formen des Feierns machen Erfolge bedeutsam.',
 'Lassen Sie Lernende mitbestimmen, wie Erfolge gefeiert werden.',
 'Nach einer bestandenen Zwischenprüfung wünscht sich die Gruppe einen gemeinsamen Tee mit Gebäck. So wird der Erfolg sichtbar gewürdigt.',
 'Sorgen Sie für Formen, die alle einbeziehen und niemanden überfordern.'),
(3, 36, 'Gruppengrösse wählen',
 'Die passende Gruppengrösse hängt von der Aufgabe ab und kann gewählt werden.',
 'Die selbst gewählte Grösse fördert Beteiligung und passt zum Arbeitsstil.',
 'Bieten Sie an, die Gruppengrösse für Aufgaben gemeinsam zu wählen.',
 'Für eine Diskussion wünscht sich die Gruppe Kleingruppen zu dritt statt im Plenum, damit alle zu Wort kommen.',
 'Behalten Sie im Blick, dass die Gruppen ausgewogen zusammengesetzt sind.'),
(3, 37, 'Ideenkiste befüllen',
 'Eine Sammelstelle für Ideen hält die Mitgestaltung dauerhaft offen.',
 'Die Ideenkiste lädt auch Zurückhaltende zur Beteiligung ein.',
 'Lassen Sie Lernende eine «Ideenkiste» für künftige Lektionen befüllen.',
 'In der Kiste landet Herr M.s Idee: «einmal kochen und dabei Deutsch sprechen». Sie greifen sie für einen Projekttag auf.',
 'Leeren Sie die Kiste regelmässig und geben Sie Rückmeldung zu den Ideen.'),
(3, 38, 'Gegenseitige Unterstützung',
 'Eine Gruppe kann vereinbaren, wie sie sich selbst hilft.',
 'Vereinbarte gegenseitige Hilfe stärkt Zusammenhalt und entlastet die Leitung.',
 'Vereinbaren Sie gemeinsam, wie sich die Gruppe gegenseitig unterstützt.',
 'Die Gruppe beschliesst Lernpatenschaften: Wer etwas gut kann, hilft anderen. Frau N. erklärt gern die Uhrzeit.',
 'Achten Sie darauf, dass Helfen freiwillig bleibt und niemand überlastet wird.'),
(3, 39, 'Sprech- und Schreibanteile',
 'Die Verteilung von Fertigkeiten kann mit der Gruppe ausgehandelt werden.',
 'Mitbestimmung über die Anteile richtet den Kurs an den Bedürfnissen aus.',
 'Lassen Sie die Gruppe über die Verteilung von Sprech- und Schreibanteilen mitentscheiden.',
 'Die Gruppe wünscht sich mehr Sprechen. Sie verschieben den Schwerpunkt und behalten das Schreiben als Hausaufgabe.',
 'Sorgen Sie dafür, dass keine Fertigkeit dauerhaft zu kurz kommt.'),
(3, 40, 'Offenen Block füllen',
 'Ein bewusst offener Teil des Plans gehört der Gruppe.',
 'Der offene Block gibt Mitgestaltung einen festen, planbaren Ort.',
 'Bieten Sie an, einen Teil des Kursplans als «offenen Block» gemeinsam zu füllen.',
 'Jeden Donnerstag ist eine Stunde offen. Die Gruppe entscheidet jeweils kurz vorher, was sie damit machen will.',
 'Schützen Sie diesen Block, damit er nicht für Stoffrückstände aufgebraucht wird.'),
(3, 41, 'Patenschaften organisieren',
 'Neue Teilnehmende lassen sich durch die Gruppe selbst integrieren.',
 'Mitorganisierte Patenschaften fördern Verantwortung und Willkommenskultur.',
 'Lassen Sie Lernende Patenschaften für neue Teilnehmende mitorganisieren.',
 'Als Herr O. neu dazukommt, übernimmt Frau P. die Patenschaft: Sie zeigt ihm Abläufe und hilft beim Nachholen.',
 'Begleiten Sie die Patenschaften, damit sie nicht ins Leere laufen.'),
(3, 42, 'Umgang mit Niveaus',
 'Unterschiedliche Niveaus sind in Integrationskursen normal und gestaltbar.',
 'Ein gemeinsam vereinbarter Umgang nimmt Druck und fördert Rücksicht.',
 'Vereinbaren Sie gemeinsam, wie mit unterschiedlichen Niveaus umgegangen wird.',
 'Die Gruppe beschliesst: Schnellere helfen Langsameren, und niemand wird gedrängt. Das Klima wird entspannter.',
 'Sorgen Sie für Aufgaben, die auf mehreren Niveaus funktionieren.'),
(3, 43, 'Ernst oder spielerisch',
 'Ein Thema lässt sich ernst oder spielerisch angehen – die Gruppe darf wählen.',
 'Die Wahl des Zugangs passt zur Tagesform und steigert die Beteiligung.',
 'Lassen Sie die Gruppe entscheiden, ob ein Thema spielerisch oder ernst angegangen wird.',
 'Beim Wortschatz Lebensmittel wählt die Gruppe ein Bewegungsspiel statt einer Liste – und merkt sich die Wörter besser.',
 'Stellen Sie sicher, dass das Lernziel auch beim spielerischen Zugang erreicht wird.'),
(3, 44, 'Bedarfs-Blitzlicht',
 'Kurze Blitzlichter erfassen schnell, was die Gruppe gerade braucht.',
 'Das regelmässige Nachfragen hält den Kurs eng an den Bedürfnissen.',
 'Bieten Sie regelmässige «Was-brauchen-Sie?»-Blitzlichter an.',
 'In einer Runde sagt jede Person ein Wort zum aktuellen Bedarf. «Übung», «Ruhe», «Sprechen» – Sie richten die Stunde danach.',
 'Halten Sie das Blitzlicht kurz, damit es nicht zur langen Diskussion wird.'),
(3, 45, 'Projekttag planen',
 'Ein ganzer Projekttag kann von der Gruppe selbst durchdacht werden.',
 'Gemeinsame Planung fördert Sprache, Organisation und Zusammenhalt zugleich.',
 'Lassen Sie Lernende den Ablauf eines Projekttags gemeinsam planen.',
 'Für den Projekttag «Einkaufen im echten Laden» plant die Gruppe Schritte, Einkaufsliste und Fragen – auf Deutsch.',
 'Geben Sie einen klaren Rahmen vor, innerhalb dessen frei geplant wird.'),
(3, 46, 'Sprachen aushandeln',
 'Wann Deutsch und wann andere Sprachen sinnvoll sind, lässt sich besprechen.',
 'Eine gemeinsame Vereinbarung nimmt Druck und respektiert die Mehrsprachigkeit.',
 'Vereinbaren Sie gemeinsam, wann Deutsch und wann andere Sprachen erlaubt sind.',
 'Die Gruppe einigt sich: Erklärungen untereinander dürfen kurz in der Erstsprache sein, geübt wird dann auf Deutsch.',
 'Würdigen Sie die Erstsprachen als Ressource, nicht als Hindernis.'),
(3, 47, 'Gäste und Exkursionen',
 'Begegnungen mit Gästen oder Orten bereichern den Kurs.',
 'Selbst eingebrachte Vorschläge machen solche Anlässe besonders relevant.',
 'Lassen Sie die Gruppe Vorschläge für Gäste oder Exkursionen einbringen.',
 'Frau Q. schlägt vor, jemanden vom Arbeitsamt einzuladen. Die Gruppe bereitet gemeinsam Fragen vor.',
 'Klären Sie Organisatorisches frühzeitig, damit Vorschläge auch umsetzbar sind.'),
(3, 48, 'Erfolge und Hürden besprechen',
 'Eine offene Runde macht Erfolge und Schwierigkeiten gemeinsam besprechbar.',
 'Das gemeinsame Reflektieren stärkt Verantwortung für den Lernprozess.',
 'Bieten Sie an, Erfolge und Schwierigkeiten in einer gemeinsamen Runde zu besprechen.',
 'In der Freitagsrunde erzählt Herr R. stolz von einem geglückten Behördengespräch; andere berichten, wo es noch hakt.',
 'Sorgen Sie für eine wertschätzende Atmosphäre, in der auch Hürden Platz haben.'),
(3, 49, 'Überprüfungen mitgestalten',
 'Auch Tests und Überprüfungen können mit der Gruppe besprochen werden.',
 'Mitgestaltete Überprüfungen nehmen Angst und schaffen Transparenz.',
 'Lassen Sie Lernende über die Gestaltung von Tests und Überprüfungen mitreden.',
 'Vor dem Zwischentest wünscht sich die Gruppe, vorher die Themen genau zu kennen. Sie legen die Schwerpunkte gemeinsam offen.',
 'Bleiben Sie bei nötigen formalen Prüfungen klar über die Rahmenbedingungen.'),
(3, 50, 'Mitnehmen und ändern',
 'Ein kurzer Wochenabschluss bündelt Erkenntnisse und Änderungswünsche.',
 'Die feste Schlussrunde macht Mitgestaltung zur regelmässigen Gewohnheit.',
 'Schliessen Sie jede Kurswoche mit einer kurzen «Das nehmen wir mit / das ändern wir»-Runde ab.',
 'Am Freitag sammelt die Gruppe: «Wir nehmen das Telefonieren mit, wir ändern: mehr Pausen.» Sie planen die Folgewoche danach.',
 'Setzen Sie mindestens einen Änderungswunsch sichtbar um, damit die Runde ernst genommen wird.')
ON CONFLICT (id) DO NOTHING;
