-- Backfill SPASS seed data.
-- This migration is idempotent and can run safely even if rows already exist.

insert into spass_gruppen (id, kuerzel, titel, beschreibung, sortierung)
values
  (1, 'Sg', 'Selbstgesteuertes Lernen', 'Lernende bestimmen Wissen, Ziele und Lernwege weitgehend selbst und überprüfen ihre Ergebnisse eigenständig. Sie übernehmen Verantwortung für den eigenen Lernprozess. Die Lehrperson schafft dafür die Rahmenbedingungen.', 1),
  (2, 'P', 'Produktives Lernen', 'Vorwissen und Vorerfahrungen der Lernenden werden bewusst einbezogen. Es entsteht Raum für Neugier, Entdeckung und unterschiedliche Perspektiven. Lernende hinterfragen dabei auch eigene Sichtweisen.', 2),
  (3, 'A', 'Aktivierendes Lernen', 'Lernende werden durch konkrete Arbeitsaufträge ins Handeln gebracht. Sie planen, erproben und überprüfen Lösungswege selbst und entwickeln eigene Initiativen. Praxis- und Erlebnisorientierung stehen im Vordergrund.', 3),
  (4, 'Si', 'Situatives Lernen', 'Das Lernen knüpft an die konkrete Hier-und-jetzt-Situation der Lerngruppe an. Methoden und Inhalte sind auf die Lernenden und ihre Praxis abgestimmt. Lösungen werden an Praxisbeispielen erarbeitet und in die eigene Praxis übertragen.', 4),
  (5, 'So', 'Soziales Lernen', 'Lernende erleben Wertschätzung und erhalten Raum für Fragen, Feedback und Emotionen. Konstruktive Kommunikation wird bewusst geübt. Die kooperative Erarbeitung von Lösungen wird gezielt gefördert.', 5)
on conflict (id) do nothing;

insert into spass_items (id, gruppe_id, item, sortierung)
values
  (1, 1, 'In meinem Kurs haben Lernende die Möglichkeit, Wissen und Lernwege selbst zu bestimmen.', 1),
  (2, 1, 'In meinem Kurs überprüfen Lernende ihre Lernergebnisse selbst.', 2),
  (3, 1, 'In meinem Kurs gestalten Lernende Ziele, Prozesse und Lernbedingungen mit.', 3),
  (4, 1, 'In meinem Kurs werden Lernende darin unterstützt, die Verantwortung für ihr Lernen selbst zu übernehmen.', 4),
  (5, 1, 'In meinem Kurs bin ich als Lehrende/Lehrender prozessverantwortlich und schaffe die Bedingungen für das gelingende Selbstlernen der Lernenden.', 5),
  (6, 2, 'In meinem Kurs werden Vorerfahrung und Vorwissen der Lernenden eingebunden.', 1),
  (7, 2, 'In meinem Kurs wird Lernenden Raum für Neugier und Entdeckungen geboten (Entdeckungsarbeit).', 2),
  (8, 2, 'In meinem Kurs nehmen Lernende unterschiedliche Perspektiven ein.', 3),
  (9, 2, 'In meinem Kurs erhalten Lernende die Möglichkeit, eigene Sichtweisen zu hinterfragen.', 4),
  (10, 3, 'In meinem Kurs bearbeiten Lernende konkrete Arbeitsaufträge.', 1),
  (11, 3, 'In meinem Kurs wird Lernenden ermöglicht, Lösungswege selbst zu planen, durchzuführen und zu überprüfen.', 2),
  (12, 3, 'In meinem Kurs entwickeln Lernende selbst Initiativen.', 3),
  (13, 3, 'In meinem Kurs wird Lernenden ermöglicht, praxis- und erlebnisorientiert zu arbeiten.', 4),
  (14, 4, 'In meinem Kurs nutzen und reflektieren Lernende die Hier-und-jetzt-Situation.', 1),
  (15, 4, 'In meinem Kurs nimmt die Methode Bezug auf die Situation der Lerngruppe und ist auf die Situation der Lernenden und der Lerngruppe abgestimmt.', 2),
  (16, 4, 'In meinem Kurs erarbeiten Lernende Lösungen anhand von Praxisbeispielen.', 3),
  (17, 4, 'In meinem Kurs übertragen Lernende Musterlösungen in die eigene Praxis.', 4),
  (18, 4, 'In meinem Kurs werden Lernenden Empfehlungen für den Praxistransfer geboten.', 5),
  (19, 5, 'In meinem Kurs erleben Lernende Wertschätzung.', 1),
  (20, 5, 'In meinem Kurs erhalten Lernende Zeit und Raum für ihre Fragen und Feedback.', 2),
  (21, 5, 'In meinem Kurs nehme ich Emotionen wahr.', 3),
  (22, 5, 'In meinem Kurs üben Lernende konstruktive Formen der Kommunikation.', 4),
  (23, 5, 'In meinem Kurs werden Lernende bei der kooperativen Erarbeitung von Lösungen gefördert.', 5)
on conflict (id) do nothing;

insert into spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig)
values
  (1, 1, 'Startthema freigeben', 'Lernen wird bedeutsam, wenn es an die Lebenswelt und die selbst gesetzten Prioritäten der Lernenden anknüpft.', 'Mitbestimmung über Inhalte erhöht das Relevanzerleben und die Motivation, weil das Thema als "meins" empfunden wird.', 'Lassen Sie die Gruppe aus mehreren Alltagsthemen wählen, womit gestartet wird - präsentieren Sie drei bis vier Felder mit Bildern und entscheiden Sie per Handzeichen oder Klebepunkt.', 'Sie zeigen vier Fotokarten - Wohnungssuche, Arzttermin, Lohnabrechnung, Elternabend. Frau A. zeigt auf den Arzttermin, weil sie nächste Woche zur Hausärztin muss; die Gruppe stimmt mit Punkten ab, "Beim Arzt" gewinnt und wird zum Wocheneinstieg.', 'Halten Sie die Auswahl klein, sonst entsteht Überforderung statt Orientierung.'),
  (1, 2, 'Lernmenü anbieten', 'Wahlmöglichkeiten innerhalb eines klaren Rahmens verbinden Freiheit mit Struktur.', 'Lernende erleben Autonomie, ohne von völliger Offenheit überfordert zu werden.', 'Stellen Sie ein "Lernmenü" bereit, von dem ein Vertiefungsthema gewählt wird - eine "Speisekarte" mit drei bis fünf Optionen zum laufenden Thema, jede/r wählt einen "Gang".', 'Zum Thema "Einkaufen" hängt eine Menükarte: Vorspeise "Preise erfragen", Hauptgang "Reklamation im Laden", Dessert "Online bestellen". Herr B. wählt die Reklamation, weil er kürzlich eine kaputte Lampe umtauschen musste.', 'Sorgen Sie dafür, dass alle Optionen sprachlich auf ähnlichem Niveau liegen.'),
  (1, 3, 'Übungsweg wählen lassen', 'Unterschiedliche Lerntypen und Zugänge führen zum selben Ziel - der Weg darf individuell sein.', 'Lernende übernehmen Verantwortung für den eigenen Zugang und arbeiten konzentrierter, weil der Kanal passt.', 'Bieten Sie zu jedem Grammatikpunkt drei Übungswege an (Hören, Lesen, Sprechen) und lassen Sie wählen, welcher zuerst bearbeitet wird.', 'Beim Perfekt liegen drei Karten bereit: ein Hörtext mit Lücken, ein Lesetext zum Markieren, eine Sprechkarte für Partnerinterviews. Frau C., die ungern liest, greift zur Sprechkarte und erzählt ihrem Nachbarn, was sie am Wochenende gemacht hat.', 'Machen Sie deutlich, dass alle Wege zum gleichen Lernziel führen, damit keine Variante als "weniger wert" gilt.'),
  (1, 4, 'Wunschthemen priorisieren', 'Partizipation wird greifbar, wenn Mitbestimmung sichtbar und niederschwellig ist.', 'Auch sprachlich schwächere Lernende können sich beteiligen, weil die Stimme nonverbal abgegeben wird.', 'Hängen Sie ein Themenplakat auf, auf dem Lernende mit Klebepunkten ihre Wunschthemen markieren; die Häufung der Punkte steuert die Planung.', 'Auf einem Plakat stehen acht Themen mit Symbolen. Jede Person klebt drei Punkte. "Arbeit suchen" und "Mit der Schule sprechen" bekommen die meisten - Sie planen die nächsten zwei Wochen sichtbar danach.', 'Machen Sie transparent, dass nicht jedes Thema sofort drankommt, um Enttäuschung zu vermeiden.'),
  (1, 5, 'Zugang frei wählen', 'Der Einstieg in einen Inhalt darf an die individuellen Stärken anknüpfen.', 'Ein selbst gewählter Zugang senkt die Einstiegshürde und stärkt das Zutrauen in die eigene Lernfähigkeit.', 'Lassen Sie Lernende entscheiden, ob sie ein Thema über Bilder, Text oder Gespräch erschliessen - stellen Sie Bildimpuls, Kurztext und Leitfrage parallel bereit.', 'Beim Thema "Mülltrennung" liegen ein Bildposter, ein kurzer Infotext und die Gesprächsfrage "Wie machen Sie das zu Hause?" bereit. Herr D. beginnt beim Gespräch und merkt, dass er den Wortschatz schon teilweise kennt.', 'Achten Sie darauf, dass alle Zugänge zur gleichen Kernaussage führen.'),
  (1, 6, 'Lernkanal freigeben', 'Wortschatzfestigung gelingt über verschiedene Methoden - die Wahl der Methode kann den Lernenden überlassen werden.', 'Selbst gewählte Festigungsmethoden werden konsequenter genutzt und besser behalten.', 'Geben Sie zu Wortschatz mehrere Lernkanäle frei (Karteikarten, App, Plakat, Partnerübung) und richten Sie dafür eine Materialecke ein.', 'In der "Wörter-Ecke" liegen Karteikarten, zwei Tablets mit einer Vokabel-App und ein leeres Plakat. Frau E. und Frau F. schreiben gemeinsam ein Wortplakat zum Thema Küche, während Herr G. allein mit der App übt.', 'Führen Sie jede Methode einmal gemeinsam ein, damit echte Wahlfreiheit besteht.'),
  (1, 7, 'Könnensziele abfragen', 'Lernziele werden tragfähig, wenn sie aus den Bedürfnissen der Lernenden hervorgehen.', 'Lernende erleben, dass ihre Anliegen den Kurs prägen - das stärkt Verantwortung und Engagement.', 'Fragen Sie regelmässig "Was möchten Sie als Nächstes können?" und greifen Sie ein genanntes Ziel sichtbar in der Folgeplanung auf.', 'Am Freitag fragen Sie in die Runde. Herr H. sagt: "Ich will einen Termin am Telefon machen." Sie notieren es und starten am Montag mit einem Telefon-Rollenspiel - Herr H. erkennt sein eigenes Anliegen wieder.', 'Halten Sie die Frage konkret ("können"), sonst bleiben die Antworten zu vage zum Planen.'),
  (1, 8, 'Eigenes Vokabelheft anlegen', 'Selbst strukturiertes Wissen wird tiefer verarbeitet als übernommenes.', 'Das Ordnen nach eigenen Kategorien verankert Wortschatz im persönlichen Bedeutungsnetz.', 'Lassen Sie Lernende ein eigenes Vokabelheft nach selbst gewählten Kategorien anlegen - geben Sie ein leeres Heft statt alphabetischer Vorgaben.', 'Frau I. legt im Heft die Rubriken "Bei der Arbeit", "Mit den Kindern" und "Schwierige Wörter" an. Neue Wörter sortiert sie selbst ein - "Schichtplan" landet bei der Arbeit, "Elternabend" bei den Kindern.', 'Begleiten Sie schreibungewohnte Lernende mit Mustern, ohne die Kategorien vorzugeben.'),
  (1, 9, 'Pflicht- und Wahlaufgaben', 'Ein gemeinsamer Kern sichert das Lernziel, Wahlaufgaben ermöglichen individuelle Vertiefung.', 'Lernende steuern Tempo und Schwerpunkt selbst und bleiben dadurch im passenden Anforderungsbereich.', 'Bieten Sie pro Lektion eine Pflicht- und mehrere Wahlaufgaben an - eine verbindliche Basis plus zwei bis drei frei wählbare Vertiefungen.', 'Alle schreiben eine kurze E-Mail an die Vermieterin (Pflicht). Wer fertig ist, wählt: das Gespräch dazu üben, schwierige Wörter sammeln oder eine höflichere Version schreiben. Herr J. nimmt die höfliche Version, weil ihn Formulierungen interessieren.', 'Sorgen Sie dafür, dass auch Schnelle und Langsame sinnvoll beschäftigt sind.'),
  (1, 10, 'Sozialform freigeben', 'Die passende Sozialform hängt von Aufgabe, Tagesform und Persönlichkeit ab und darf gewählt werden.', 'Selbst gewählte Sozialformen erhöhen Wohlbefinden und Sprechbereitschaft im Kurs.', 'Lassen Sie Lernende bestimmen, ob sie allein, zu zweit oder in der Gruppe arbeiten - markieren Sie dafür Zonen im Raum für Einzel-, Partner- und Gruppenarbeit.', 'Für die Übung zum Wegbeschreiben markieren Sie drei Zonen. Frau K. geht in die Partnerzone und übt mit einer Kollegin, Herr L. setzt sich allein in die "Ruhe-Ecke", weil er erst für sich formulieren möchte.', 'Behalten Sie im Blick, dass niemand dauerhaft allein bleibt, der eigentlich Anschluss sucht.')
on conflict (item_id, nr) do nothing;
