-- =========================================================
-- SEED: Tipps zu Item 2 (Nr. 1–50)
-- «In meinem Kurs überprüfen Lernende ihre Lernergebnisse selbst.»
-- =========================================================
INSERT INTO spass_tipps (item_id, nr, kurztitel, grundlage, wirkung, umsetzung, praxisbeispiel, wichtig) VALUES
(2, 1, 'Lösungsblatt bereitstellen',
 'Selbstkontrolle setzt voraus, dass Lernende Zugang zur Lösung haben.',
 'Der eigene Abgleich mit der Lösung fördert genaues Hinschauen und Selbstständigkeit.',
 'Stellen Sie Lösungsblätter zur Selbstkontrolle bereit, die Lernende nach der Aufgabe selbst abholen.',
 'Nach den Übungen zum Dativ holt sich Frau A. das Lösungsblatt vom Pult und vergleicht Satz für Satz, bevor sie zu Ihnen kommt.',
 'Legen Sie die Lösungen erst nach der Bearbeitung aus, damit nicht vorab abgeschrieben wird.'),
(2, 2, 'Erst selbst prüfen',
 'Wer zuerst selbst kontrolliert, übernimmt Verantwortung für die eigene Arbeit.',
 'Selbstprüfung schult das Auge für eigene Fehler und reduziert reine Abhängigkeit von Korrektur.',
 'Lassen Sie Lernende ihre Antworten zuerst selbst prüfen, bevor Sie korrigieren.',
 'Bevor Herr B. sein Blatt abgibt, geht er es nochmal durch und findet selbst zwei vergessene Verbendungen.',
 'Geben Sie eine konkrete Prüf-Anweisung, sonst bleibt das «Selbstprüfen» oberflächlich.'),
(2, 3, 'Ich-kann-Checkliste',
 'Lernziele werden überprüfbar, wenn sie als konkrete Könnens-Aussagen formuliert sind.',
 'Das Abhaken macht Fortschritt sichtbar und stärkt das Gefühl von Kompetenz.',
 'Geben Sie eine «Ich kann …»-Checkliste zum Abhaken nach jeder Lektion aus.',
 'Auf der Liste steht «Ich kann nach dem Weg fragen». Frau C. hakt es ab, nachdem sie es im Rollenspiel geschafft hat.',
 'Formulieren Sie die Punkte konkret und beobachtbar, nicht als vage «Ich verstehe …».'),
(2, 4, 'Aussprache aufnehmen',
 'Die eigene Aussprache wird beurteilbar, wenn man sie hört statt nur spricht.',
 'Der Vergleich mit einem Modell schärft das Gehör für die eigene Aussprache.',
 'Lassen Sie Lernende ihre Aussprache mit einer App-Aufnahme selbst mit einem Modell vergleichen.',
 'Herr D. nimmt den Satz «Ich möchte einen Termin» auf, hört das Modell und merkt selbst, dass sein «ö» noch übungsbedürftig ist.',
 'Schaffen Sie eine ruhige Ecke, damit die Aufnahmen nicht zu sehr stören.'),
(2, 5, 'Lösungskarten an Stationen',
 'Stationenlernen lebt von eingebauter Selbstkontrolle an Ort und Stelle.',
 'Sofortige Kontrolle hält den Lernfluss aufrecht und gibt unmittelbare Rückmeldung.',
 'Bieten Sie Lösungskarten an Stationen an, an denen selbstständig kontrolliert wird.',
 'An der Wortschatzstation liegt die Lösungskarte umgedreht bereit. Frau E. dreht sie erst um, wenn sie fertig ist, und korrigiert selbst.',
 'Platzieren Sie die Lösung so, dass sie nicht beim Bearbeiten ins Auge fällt.'),
(2, 6, 'Kriterienliste für Texte',
 'Schreibprodukte lassen sich an klaren, einfachen Kriterien selbst prüfen.',
 'Eine Kriterienliste lenkt den Blick gezielt auf das, was zählt.',
 'Lassen Sie Lernende ihre Texte anhand einer einfachen Kriterienliste selbst überprüfen.',
 'Nach dem Schreiben einer E-Mail prüft Herr F. mit der Liste: Anrede da? Gruss da? Verb am Ende des Nebensatzes? Er ergänzt den vergessenen Gruss.',
 'Halten Sie die Liste kurz (drei bis vier Punkte), sonst überfordert sie.'),
(2, 7, 'Lernportfolio führen',
 'Fortschritt wird sichtbar, wenn Produkte über die Zeit gesammelt werden.',
 'Das eigene Portfolio macht Entwicklung erlebbar und stärkt das Selbstvertrauen.',
 'Führen Sie ein Lernportfolio ein, in dem eigene Fortschritte gesammelt werden.',
 'Frau G. heftet jede Woche einen Text ab. Nach zwei Monaten blättert sie zurück und sieht selbst, wie viel sicherer sie schreibt.',
 'Vereinbaren Sie feste Zeiten fürs Einheften, sonst bleibt das Portfolio leer.'),
(2, 8, 'Alt und neu vergleichen',
 'Lernfortschritt wird greifbar im direkten Vergleich von früher und heute.',
 'Der Vergleich macht den eigenen Zuwachs konkret und motiviert weiterzumachen.',
 'Lassen Sie Lernende ein altes Arbeitsblatt mit einem neuen vergleichen («Was kann ich jetzt mehr?»).',
 'Herr H. legt sein Diktat von vor sechs Wochen neben das aktuelle und zählt selbst, wie viele Fehler weniger es geworden sind.',
 'Wählen Sie vergleichbare Aufgaben, sonst hinkt der Vergleich.'),
(2, 9, 'Selbsttest mit Rückmeldung',
 'Kurze Selbsttests geben sofortige, unabhängige Rückmeldung über den Lernstand.',
 'Unmittelbares Feedback ohne Bewertungsdruck fördert ehrliche Selbsteinschätzung.',
 'Geben Sie Selbsttest-Quizze (Papier oder App) mit sofortiger Rückmeldung aus.',
 'Frau I. macht ein kurzes Online-Quiz zu den Wochentagen und sieht direkt, dass sie «Mittwoch» und «Donnerstag» noch verwechselt.',
 'Sorgen Sie für eine analoge Variante, falls nicht alle ein Gerät haben.'),
(2, 10, 'Sicherheit einschätzen',
 'Vor der Korrektur lohnt sich die Einschätzung der eigenen Sicherheit.',
 'Das bewusste Einschätzen schult die metakognitive Selbstwahrnehmung.',
 'Lassen Sie Lernende vor der Korrektur ihre Sicherheit einschätzen (Daumen hoch/seitlich/runter).',
 'Vor der Auflösung zeigt Herr J. den Daumen zur Seite – unsicher. Nach dem Abgleich stimmt es doch, und seine Freude ist umso grösser.',
 'Werten Sie keine Einschätzung ab – Unsicherheit zuzugeben ist eine Stärke.'),
(2, 11, 'Lösungsecke zum Nachschlagen',
 'Selbstkontrolle gelingt, wenn Hilfsmittel zum Nachschlagen bereitstehen.',
 'Eigenständiges Nachschlagen fördert Unabhängigkeit und Recherchekompetenz.',
 'Bieten Sie eine Lösungsecke mit Wörterbüchern an, in der selbst nachgeschlagen wird.',
 'Unsicher bei der Schreibweise von «Quittung» geht Frau K. in die Lösungsecke und schlägt das Wort selbst nach, statt zu fragen.',
 'Zeigen Sie einmal, wie man im Wörterbuch sucht, damit die Ecke wirklich genutzt wird.'),
(2, 12, 'Fehlerheft führen',
 'Wiederkehrende Fehler werden bewusst, wenn man sie sammelt.',
 'Das eigene Fehlerheft macht Muster sichtbar und gezielt bearbeitbar.',
 'Lassen Sie Lernende ein eigenes Fehlerheft führen und wiederkehrende Fehler markieren.',
 'Herr L. trägt jeden korrigierten Fehler ein. Nach einiger Zeit sieht er: Fast immer fehlt das «n» im Dativ Plural – sein persönlicher Schwerpunkt.',
 'Begleiten Sie das Sortieren der Fehler, damit das Heft nicht zur reinen Sammlung wird.'),
(2, 13, 'Modelltext vergleichen',
 'Eigene Texte lassen sich am Modell auf Vollständigkeit und Form prüfen.',
 'Der Vergleich mit einem Muster zeigt konkret, was noch fehlt.',
 'Geben Sie Modelltexte aus, mit denen die eigene Schreibaufgabe verglichen wird.',
 'Nach ihrer Entschuldigung an die Schule vergleicht Frau M. mit dem Modell und ergänzt das fehlende Datum.',
 'Machen Sie klar, dass das Modell Orientierung ist, nicht eine Vorlage zum Abschreiben.'),
(2, 14, 'Karteikarten dreiteilen',
 'Wortschatzkontrolle gelingt durch Sortieren in sicher, unsicher und neu.',
 'Das Dreiteilen lenkt das Üben gezielt auf die unsicheren Wörter.',
 'Lassen Sie Lernende ihren Wortschatz mit Karteikarten selbst abfragen (drei Stapel: sicher/unsicher/neu).',
 'Herr N. legt «Brot» auf «sicher», «Quittung» auf «unsicher». Beim nächsten Durchgang übt er nur den unsicheren Stapel.',
 'Lassen Sie die Stapel regelmässig neu sortieren, damit «sicher» wirklich sicher bleibt.'),
(2, 15, 'Lernziel-Ampel',
 'Am Lektionsende lässt sich der Lernstand schnell selbst einordnen.',
 'Die Ampel gibt eine niederschwellige, sofortige Selbsteinschätzung.',
 'Führen Sie kurze «Lernziel erreicht?»-Ampeln am Lektionsende ein (grün/gelb/rot).',
 'Zum Schluss zeigt Frau O. ihre gelbe Karte zum Thema Uhrzeit – sie braucht noch etwas Übung, und Sie planen es ein.',
 'Reagieren Sie sichtbar auf «rot» und «gelb», sonst verliert die Ampel ihren Sinn.'),
(2, 16, 'Eigene Aufnahme anhören',
 'Die eigene Sprechleistung wird beurteilbar, wenn man sie selbst hört.',
 'Das Anhören mit konkretem Ziel fördert gezielte Selbstkorrektur.',
 'Lassen Sie Lernende eigene Audioaufnahmen anhören und eine Sache zum Verbessern finden.',
 'Herr P. hört seine Vorstellung an und beschliesst selbst: «Ich spreche zu schnell, nächstes Mal langsamer.»',
 'Begrenzen Sie auf einen Verbesserungspunkt, damit es nicht entmutigt.'),
(2, 17, 'Selbstlernsoftware nutzen',
 'Digitale Übungsprogramme geben direktes, geduldiges Feedback.',
 'Sofortrückmeldung im eigenen Tempo entlastet und ermöglicht häufiges Üben.',
 'Bieten Sie ein Tablet mit Selbstlernsoftware an, die direkt Feedback gibt.',
 'Frau Q. übt am Tablet Artikel. Bei jedem Fehler erscheint sofort die richtige Lösung – sie probiert, bis es sitzt.',
 'Wählen Sie Programme, die Fehler erklären, nicht nur als falsch markieren.'),
(2, 18, 'Hausaufgaben selbst kontrollieren',
 'Auch zu Hause ist Selbstkontrolle mit dem passenden Schlüssel möglich.',
 'Eigenständige Kontrolle zu Hause stärkt Verantwortung und spart Kurszeit.',
 'Lassen Sie Lernende ihre Hausaufgaben mit dem bereitgestellten Lösungsschlüssel kontrollieren.',
 'Herr R. korrigiert seine Übungen zu Hause selbst und bringt nur die zwei Stellen mit, die er nicht versteht.',
 'Besprechen Sie nur die offenen Fragen, nicht jede Aufgabe – das würdigt die Selbstkontrolle.'),
(2, 19, 'Drei-Stufen-Skala',
 'Lernstände lassen sich in einfachen Stufen selbst einordnen.',
 'Eine klare Skala macht Selbsteinschätzung schnell und ehrlich.',
 'Geben Sie eine Skala aus («Das schaffe ich allein / mit Hilfe / noch nicht»).',
 'Zur Wegbeschreibung kreuzt Frau S. «mit Hilfe» an. Sie weiss damit selbst, dass sie noch eine Stütze braucht.',
 'Verbinden Sie jede Stufe mit einem nächsten Schritt, damit die Einschätzung folgenreich ist.'),
(2, 20, 'Wochen-Lernnotiz',
 'Das Festhalten des Gelernten macht den Lernstand bewusst.',
 'Das Aufschreiben am Wochenende festigt und reflektiert das Gelernte.',
 'Lassen Sie Lernende am Wochenende eine «Was-habe-ich-gelernt»-Notiz schreiben.',
 'Herr T. notiert: «Ich kann jetzt einen Arzttermin machen.» Beim Lesen merkt er selbst, wie viel er kann.',
 'Halten Sie die Notiz kurz, damit sie zur Gewohnheit wird statt zur Pflicht.'),
(2, 21, 'Vorher-Nachher-Diktat',
 'Derselbe Text zu zwei Zeitpunkten zeigt den Lernzuwachs objektiv.',
 'Der direkte Vergleich macht Fortschritt unbestreitbar sichtbar.',
 'Bieten Sie Vorher-Nachher-Diktate an, die selbst verglichen werden.',
 'Am Kursanfang schreibt Frau U. ein kurzes Diktat, nach vier Wochen dasselbe. Sie zählt selbst die Verbesserung und freut sich.',
 'Heben Sie das erste Diktat sicher auf, damit der Vergleich später möglich ist.'),
(2, 22, 'Wochenziele markieren',
 'Selbst gesetzte Ziele lassen sich selbst auf Erreichung prüfen.',
 'Das eigene Markieren von erreicht/offen stärkt Verantwortung für die Ziele.',
 'Lassen Sie Lernende ihre Lernziele der Woche selbst als erreicht oder offen markieren.',
 'Herr V. hakt «Termin am Telefon machen» ab, lässt «E-Mail schreiben» offen – und nimmt es sich für nächste Woche vor.',
 'Würdigen Sie auch Teilerfolge, damit «offen» nicht entmutigt.'),
(2, 23, 'Gesprächskriterien anlegen',
 'Mündliche Leistung wird beurteilbar an vorab geklärten Kriterien.',
 'Klare Kriterien geben der Selbsteinschätzung von Gesprächen Halt.',
 'Geben Sie Kriterien für ein gutes Gespräch aus, an denen die eigene Leistung gemessen wird.',
 'Nach dem Rollenspiel prüft Frau W.: Habe ich gegrüsst? Nachgefragt? Mich bedankt? Sie merkt, dass sie das Nachfragen vergessen hat.',
 'Beschränken Sie sich auf wenige, beobachtbare Kriterien.'),
(2, 24, 'Eigenen Test gestalten',
 'Wer einen Test selbst erstellt, durchdringt den Stoff besonders tief.',
 'Das Gestalten eigener Aufgaben festigt Inhalte und fördert Selbstüberprüfung.',
 'Lassen Sie Lernende einen kurzen Selbsttest gestalten und sich selbst abfragen.',
 'Herr X. schreibt sich fünf Fragen zum Wortfeld Arbeit auf und prüft am nächsten Tag, was er noch weiss.',
 'Geben Sie ein Muster vor, damit das Erstellen nicht zu schwierig wird.'),
(2, 25, 'Lerntagebuch mit Leitfragen',
 'Regelmässige Reflexion verankert sich über feste Leitfragen.',
 'Leitfragen lenken die Selbstbeobachtung auf das Wesentliche.',
 'Führen Sie ein «Lerntagebuch» mit drei Leitfragen pro Woche ein.',
 'Frau Y. beantwortet wöchentlich: Was kann ich neu? Was war schwer? Was übe ich nächste Woche? – und plant daraus ihr eigenes Lernen.',
 'Halten Sie die Fragen über Wochen gleich, damit Vergleich möglich wird.'),
(2, 26, 'Bildkarten zur Selbstprüfung',
 'Wortschatz lässt sich mit Bildern ohne fremde Hilfe abfragen.',
 'Bildgestützte Selbstabfrage funktioniert auch ohne starke Schreibkompetenz.',
 'Lassen Sie Lernende anhand von Bildkarten prüfen, welchen Wortschatz sie schon benennen können.',
 'Herr Z. legt sich Bildkarten zum Thema Körper hin und benennt jedes Bild – «Arm» sitzt, bei «Ellbogen» stockt er und übt nach.',
 'Stellen Sie sicher, dass die Bilder eindeutig sind, sonst entstehen Missverständnisse.'),
(2, 27, 'Lückentext mit Lösung',
 'Selbstkontrolle gelingt, wenn die Lösung gleich mitgeliefert wird.',
 'Die Lösung auf der Rückseite ermöglicht sofortigen, eigenständigen Abgleich.',
 'Bieten Sie Lückentexte mit Lösung auf der Rückseite zur Selbstkontrolle an.',
 'Frau A. füllt einen Lückentext zu Präpositionen aus und dreht das Blatt um – zwei Lücken korrigiert sie selbst.',
 'Bitten Sie darum, erst nach dem Ausfüllen umzudrehen, und vertrauen Sie darauf.'),
(2, 28, 'Sprachnachricht bewerten',
 'Abstand schärft den Blick auf die eigene Sprechleistung.',
 'Die spätere Bewertung der eigenen Aufnahme fördert distanzierte Selbstreflexion.',
 'Lassen Sie Lernende eine eigene Sprachnachricht aufnehmen und am nächsten Tag selbst bewerten.',
 'Herr B. nimmt abends eine Wegbeschreibung auf und hört sie morgens – mit frischem Ohr fallen ihm zwei Stellen zum Verbessern auf.',
 'Geben Sie eine einfache Leitfrage zum Bewerten mit, etwa «Ist alles verständlich?».'),
(2, 29, 'Niveau selbst einordnen',
 'Eine vereinfachte Niveaubeschreibung macht Selbsteinordnung möglich.',
 'Die eigene Einordnung schafft Orientierung über den persönlichen Stand.',
 'Geben Sie eine Niveaubeschreibung (vereinfacht) aus, an der man sich selbst einordnet.',
 'Frau C. liest «Ich kann einfache Fragen stellen und beantworten» und erkennt: Das schaffe ich schon – der nächste Punkt ist mein Ziel.',
 'Übersetzen Sie die Niveaubeschreibung in einfache Sprache, sonst bleibt sie abstrakt.'),
(2, 30, 'Schreibmappe vergleichen',
 'Gesammelte Schreibprodukte zeigen Entwicklung über die Zeit.',
 'Der Blick in die eigene Mappe macht langfristigen Fortschritt erlebbar.',
 'Lassen Sie Lernende ihre Schreibprodukte über die Zeit in einer Mappe sammeln und vergleichen.',
 'Herr D. blättert seine Mappe durch und sieht, dass seine Sätze von Monat zu Monat länger und sicherer geworden sind.',
 'Datieren Sie jedes Produkt, damit die zeitliche Entwicklung ablesbar ist.'),
(2, 31, 'Kontrollstationen einbauen',
 'Im Stationenlernen gehört die Selbstkontrolle als eigene Station dazu.',
 'Eine feste Kontrollstation macht den Abgleich zur selbstverständlichen Routine.',
 'Bieten Sie «Kontrollstationen» im Stationenlernen an, an denen man die Lösung selbst abgleicht.',
 'Nach drei Übungsstationen geht Frau E. zur Kontrollstation, gleicht ab und notiert, was sie nochmal anschauen will.',
 'Trennen Sie Übungs- und Kontrollstation räumlich, damit Bearbeiten und Prüfen klar bleiben.'),
(2, 32, 'Schwierige Aufgaben einschätzen',
 'Vor einem Test lässt sich der eigene Übungsbedarf selbst bestimmen.',
 'Die Einschätzung lenkt die verbleibende Übungszeit auf das Wesentliche.',
 'Lassen Sie Lernende vor einem Test selbst einschätzen, welche Aufgaben noch schwierig sind.',
 'Herr F. geht die Themenliste durch und markiert «Trennbare Verben» als schwierig – genau die übt er am Abend vorher.',
 'Bieten Sie zu den markierten Themen gezielt Übungsmaterial an.'),
(2, 33, 'Stolperwörter sammeln',
 'Persönlich schwierige Wörter sind individuell und lassen sich selbst sammeln.',
 'Die eigene Stolperwörter-Liste richtet das Üben auf echte persönliche Hürden.',
 'Geben Sie eine «Stolperwörter»-Liste aus, in der eigene schwierige Wörter gesammelt werden.',
 'Frau G. sammelt Wörter, die ihr immer wieder schwerfallen: «Möglichkeit», «pünktlich», «Versicherung». Daraus wird ihr persönliches Übungsset.',
 'Greifen Sie die Stolperwörter ab und zu spielerisch im Kurs auf.'),
(2, 34, 'Notizen mit Modell vergleichen',
 'Eigene Mitschriften lassen sich an einem Modell auf Vollständigkeit prüfen.',
 'Der Abgleich zeigt, was beim Mitschreiben gefehlt hat.',
 'Lassen Sie Lernende ein Foto ihrer Notizen mit einem Modell vergleichen.',
 'Herr H. fotografiert seine Tafelnotizen und vergleicht sie mit dem ausgeteilten Modell – er ergänzt zwei vergessene Beispiele.',
 'Achten Sie darauf, dass das Modell wirklich vorbildlich und lesbar ist.'),
(2, 35, 'Punkteraster fürs Sprechen',
 'Sprechleistung wird greifbarer mit einem einfachen Punkteraster.',
 'Das Raster gibt der mündlichen Selbsteinschätzung eine klare Struktur.',
 'Bieten Sie ein einfaches Punkteraster für Sprechübungen zur Selbsteinschätzung an.',
 'Nach dem Gespräch gibt sich Frau I. selbst Punkte: Verständlichkeit gut, Tempo zu schnell, Wortschatz okay. Sie weiss nun, woran sie arbeitet.',
 'Halten Sie das Raster wertschätzend, damit es nicht zur strengen Benotung wird.'),
(2, 36, 'Aufgabe später wiederholen',
 'Dieselbe Aufgabe nach Wochen zeigt, was wirklich behalten wurde.',
 'Der zeitversetzte Vergleich macht nachhaltiges Lernen sichtbar.',
 'Lassen Sie Lernende eine alte Aufgabe nach zwei Wochen erneut lösen und vergleichen.',
 'Herr J. löst eine Übung zu den Wochentagen erneut – diesmal ohne Fehler, und er sieht selbst seinen Fortschritt.',
 'Wählen Sie Aufgaben, die das Wiederholen lohnen, nicht beliebige.'),
(2, 37, 'Transkript zur Hörkontrolle',
 'Nach dem Hören erlaubt das Transkript eine genaue Selbstkontrolle.',
 'Der Abgleich mit dem Text zeigt, was beim Hören verstanden wurde.',
 'Geben Sie nach Hörübungen die Transkripte zur eigenen Kontrolle aus.',
 'Nach einer Durchsage vergleicht Frau K. ihre Antworten mit dem Transkript und sieht, dass sie die Zahl falsch gehört hat.',
 'Geben Sie das Transkript erst nach dem Hören aus, nicht währenddessen.'),
(2, 38, 'Lernziel-Smileys',
 'Sicherheit bei Lernzielen lässt sich niederschwellig mit Smileys ausdrücken.',
 'Die Smiley-Markierung ist schnell und auch ohne viel Sprache machbar.',
 'Lassen Sie Lernende mit Smileys markieren, wie sicher sie sich bei jedem Lernziel fühlen.',
 'Auf der Zielliste malt Herr L. einen lächelnden Smiley zu «sich vorstellen» und einen neutralen zu «Termine vereinbaren».',
 'Reagieren Sie auf neutrale und traurige Smileys mit konkreten Übungsangeboten.'),
(2, 39, 'Selbstcheck-Box',
 'Eine Sammlung kurzer Tests erlaubt Überprüfung zu allen Themen jederzeit.',
 'Der freie Zugriff fördert eigenverantwortliche Wiederholung.',
 'Bieten Sie eine «Selbstcheck-Box» mit kurzen Tests zu allen bisherigen Themen an.',
 'In einer ruhigen Phase zieht Frau M. einen Check zum Thema Einkaufen und prüft selbst, ob sie es noch kann.',
 'Legen Sie zu jedem Check die Lösung bei, damit echte Selbstkontrolle möglich ist.'),
(2, 40, 'Lernkurve einzeichnen',
 'Fortschritt wird greifbar, wenn er als Kurve sichtbar gemacht wird.',
 'Die eigene Lernkurve visualisiert Entwicklung und motiviert.',
 'Lassen Sie Lernende ihre Fortschritte auf einer persönlichen Lernkurve einzeichnen.',
 'Herr N. trägt nach jedem Selbsttest einen Punkt ein. Die steigende Linie zeigt ihm schwarz auf weiss, dass er besser wird.',
 'Betonen Sie, dass auch Plateaus normal sind, damit die Kurve nicht entmutigt.'),
(2, 41, 'Eigene Grenze finden',
 'Gestufte Aufgaben helfen, das eigene aktuelle Leistungsniveau zu erkennen.',
 'Das Finden der eigenen Grenze fördert realistische Selbsteinschätzung.',
 'Geben Sie Aufgaben mit mehreren Schwierigkeitsstufen aus, damit man die eigene Grenze findet.',
 'Frau O. arbeitet sich durch die Stufen, bis es schwierig wird – dort weiss sie: Hier liegt aktuell meine Grenze.',
 'Vermitteln Sie, dass eine Grenze zu finden ein Erfolg ist, kein Scheitern.'),
(2, 42, 'Typische Fehler suchen',
 'Vor der Abgabe lohnt sich die gezielte Suche nach den eigenen Mustern.',
 'Das aktive Fehlersuchen schult den Blick für wiederkehrende Stolperstellen.',
 'Lassen Sie Lernende vor der Abgabe selbst drei typische Fehler bei sich suchen.',
 'Herr P. weiss, dass er oft das Verb vergisst. Er sucht gezielt danach und findet tatsächlich zwei fehlende Verben.',
 'Helfen Sie jedem, seine zwei bis drei persönlichen «Lieblingsfehler» zu kennen.'),
(2, 43, 'Drei-Sterne-System',
 'Die eigene Wochenleistung lässt sich einfach mit Sternen bewerten.',
 'Eine eigene Bewertung fördert regelmässige Rückschau ohne Notendruck.',
 'Bieten Sie ein «Drei-Sterne-System» an, mit dem die eigene Wochenleistung bewertet wird.',
 'Frau Q. gibt sich für diese Woche zwei Sterne und notiert: «Hausaufgaben gut, Sprechen zu wenig geübt.»',
 'Lassen Sie die Bewertung privat, wenn jemand sie nicht teilen möchte.'),
(2, 44, 'Verständlichkeit einschätzen',
 'Das wichtigste Ziel beim Sprechen ist, verstanden zu werden.',
 'Die Selbsteinschätzung der Verständlichkeit lenkt auf das Wesentliche.',
 'Lassen Sie Lernende ihre gesprochenen Sätze auf Verständlichkeit selbst einschätzen.',
 'Nach dem Rollenspiel überlegt Herr R.: «Hat mich meine Partnerin verstanden?» – Sie nickt, und er weiss: Das Ziel ist erreicht.',
 'Stellen Sie Verständlichkeit über Fehlerfreiheit, damit der Fokus stimmt.'),
(2, 45, 'Kann-ich-übe-ich-Blatt',
 'Ein einfaches Reflexionsblatt trennt Beherrschtes von Übungsbedarf.',
 'Die Zweiteilung macht den nächsten Lernschritt klar.',
 'Geben Sie ein Reflexionsblatt mit «Das kann ich / Das übe ich noch» aus.',
 'Frau S. ordnet «sich begrüssen» unter «Das kann ich» und «am Telefon sprechen» unter «Das übe ich noch».',
 'Greifen Sie das «Das übe ich noch» in der Planung sichtbar auf.'),
(2, 46, 'Aussprache filmen',
 'Ein kurzer Videoclip macht auch Mundbild und Haltung beim Sprechen sichtbar.',
 'Das Beobachten der eigenen Aussprache im Video schärft die Selbstwahrnehmung.',
 'Lassen Sie Lernende einen kurzen Videoclip ihrer Aussprache aufnehmen und beobachten.',
 'Herr T. filmt sich beim Satz «Wie spät ist es?» und sieht, dass er den Mund beim «ü» kaum rundet – er übt es nach.',
 'Holen Sie das Einverständnis ein und stellen Sie sicher, dass die Clips privat bleiben.'),
(2, 47, 'Freiwillige Modulkontrolle',
 'Nach jedem Modul kann eine freiwillige Überprüfung den Stand klären.',
 'Freiwilligkeit nimmt den Druck und fördert ehrliche Selbstkontrolle.',
 'Bieten Sie nach jedem Modul eine freiwillige Selbstüberprüfung an.',
 'Nach dem Modul Gesundheit nutzt Frau U. den freiwilligen Check und merkt, dass sie die Körperteile sicher beherrscht.',
 'Werten Sie die Ergebnisse nicht für Noten, sonst leidet die Ehrlichkeit.'),
(2, 48, 'Lösung selbst begründen',
 'Wer die eigene Lösung begründet, prüft sie zugleich auf Stimmigkeit.',
 'Das Begründen vor der Musterlösung vertieft das Verständnis.',
 'Lassen Sie Lernende ihre eigenen Lösungen begründen, bevor die Musterlösung kommt.',
 'Herr V. erklärt, warum er «dem Mann» schreibt: «Wem? Das ist Dativ.» Erst danach zeigen Sie die Lösung – er hatte recht.',
 'Würdigen Sie gute Begründungen auch dann, wenn das Ergebnis falsch war.'),
(2, 49, 'Wortschatz-Bingo',
 'Spielerische Selbstprüfung zeigt vergnüglich, welcher Wortschatz sitzt.',
 'Bingo verbindet Selbstkontrolle mit Freude und senkt die Hemmschwelle.',
 'Geben Sie eine Wortschatz-Bingo-Karte aus, mit der man selbst prüft, was sitzt.',
 'Frau W. streicht jedes Wort durch, das sie sicher übersetzen kann. Die zwei übrigen Felder zeigen ihr, was sie noch üben muss.',
 'Gestalten Sie das Bingo so, dass es um Können geht, nicht um Tempo.'),
(2, 50, 'Anfangsblatt wiederholen',
 'Das erste Arbeitsblatt am Kursende wiederholt zeigt den gesamten Weg.',
 'Der Vergleich mit dem Anfang macht den grossen Fortschritt sichtbar.',
 'Lassen Sie Lernende am Kursende ihr Anfangsblatt wiederholen und den Fortschritt selbst sehen.',
 'Herr X. löst das Blatt aus der ersten Woche erneut – diesmal fast fehlerfrei. Sein Staunen über sich selbst ist gross.',
 'Bewahren Sie die Anfangsblätter zentral auf, damit sie am Ende verfügbar sind.')
ON CONFLICT (id) DO NOTHING;
